"use client";
import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { CheckCircle2, Plus, Wrench } from "lucide-react";
import { createInventoryMaintenance, fetchInventoryAssets, fetchInventoryMaintenance, resolveInventoryMaintenance } from "@/lib/backend";
import { PageHeader } from "@/components/design-system";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
export default function InventoryMaintenancePage(){const q=useQueryClient();const [open,setOpen]=useState(false);const tickets=useQuery({queryKey:["inventory-maintenance"],queryFn:fetchInventoryMaintenance});const assets=useQuery({queryKey:["inventory-assets"],queryFn:()=>fetchInventoryAssets()});const refresh=()=>q.invalidateQueries({queryKey:["inventory-maintenance"]});return <div className="space-y-6"><PageHeader eyebrow="Ciclo de vida" title="Mantenimiento de activos" description="Gestiona trabajos preventivos y correctivos, costes y SLA." actions={<Button onClick={()=>setOpen(true)}><Plus className="size-4"/>Registrar mantenimiento</Button>}/><div className="grid gap-3 lg:grid-cols-2">{tickets.data?.map(t=><Card key={t.id} level={2}><CardContent className="p-5"><p className="font-semibold">{t.title}</p><p className="text-sm text-text-secondary">{t.asset.item.name} · {t.asset.assetTag} · {t.asset.branch.name}</p><p className="mt-2 text-sm">{t.type} · {t.status} {t.dueAt?`· vence ${new Date(t.dueAt).toLocaleDateString()}`:""}</p>{t.status==="OPEN"?<Button className="mt-3" size="sm" variant="secondary" onClick={()=>resolveInventoryMaintenance(t.id).then(refresh)}><CheckCircle2 className="size-4"/>Resolver</Button>:null}</CardContent></Card>)}</div><MaintenanceDialog open={open} assets={assets.data??[]} onClose={()=>setOpen(false)} onSuccess={async()=>{await refresh();setOpen(false);}}/></div>}
function MaintenanceDialog({open,assets,onClose,onSuccess}:{open:boolean;assets:Array<{id:string;assetTag:string;item:{name:string}}> ;onClose:()=>void;onSuccess:()=>Promise<void>}){const [v,setV]=useState<Record<string,string>>({type:"CORRECTIVO"});const m=useMutation({mutationFn:()=>createInventoryMaintenance({assetId:v.assetId,title:v.title,type:v.type,dueAt:v.dueAt||undefined,costAmount:v.cost?Number(v.cost):undefined,vendor:v.vendor,description:v.description}),onSuccess});return <Dialog open={open} onOpenChange={x=>!x&&onClose()}><DialogContent><DialogHeader><DialogTitle>Nuevo mantenimiento</DialogTitle></DialogHeader><div className="space-y-3"><Label>Activo</Label><Select value={v.assetId} onValueChange={x=>setV({...v,assetId:x})}><SelectTrigger><SelectValue placeholder="Seleccionar"/></SelectTrigger><SelectContent>{assets.map(a=><SelectItem key={a.id} value={a.id}>{a.item.name} · {a.assetTag}</SelectItem>)}</SelectContent></Select>{[["Título","title"],["Tipo","type"],["Fecha objetivo","dueAt"],["Coste estimado","cost"],["Proveedor","vendor"],["Descripción","description"]].map(([l,k])=><div key={k}><Label>{l}</Label><Input type={k==="dueAt"?"date":"text"} value={v[k]??""} onChange={e=>setV({...v,[k]:e.target.value})}/></div>)}<Button className="w-full" disabled={m.isPending} onClick={()=>m.mutate()}><Wrench className="size-4"/>Crear</Button></div></DialogContent></Dialog>}
