import Link from "next/link";
import { ArrowRight, BarChart3, BriefcaseBusiness, Building2, Check, ClipboardCheck, GraduationCap, PackageCheck, Users } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";

const modules = [
  { icon: BriefcaseBusiness, title: "Reclutamiento", copy: "Publica vacantes, recibe candidatos y administra cada etapa de selección.", features: ["Vacantes y postulaciones", "Pipeline e entrevistas", "Evaluaciones y ofertas"] },
  { icon: ClipboardCheck, title: "Onboarding", copy: "Centraliza tareas, documentos, responsables y el avance de cada incorporación.", features: ["Checklists operativos", "Documentos y evidencias", "Firma y seguimiento"] },
  { icon: GraduationCap, title: "Capacitación", copy: "Crea cursos, rutas y evaluaciones para preparar a tu equipo.", features: ["Contenido y SCORM", "Evaluaciones", "Certificados"] },
  { icon: PackageCheck, title: "Inventario", copy: "Controla activos, entregas y devoluciones por empleado y sucursal.", features: ["Catálogo de activos", "Custodia", "Trazabilidad"] },
  { icon: BarChart3, title: "Productividad", copy: "Consulta prioridades, alertas e indicadores para decidir con contexto.", features: ["Dashboard por rol", "SLA y alertas", "Reportes"] },
];
const lifecycle = ["Vacante", "Postulación", "Entrevista", "Contratación", "Onboarding", "Capacitación", "Empleado", "Productividad"];

export function HeroSection() { return <section className="grid gap-10 py-8 lg:grid-cols-[1.05fr_.95fr] lg:items-center lg:py-14"><div className="space-y-7"><Badge className="w-fit border border-cyan-300/20 bg-cyan-300/10 text-cyan-100">Una plataforma para todo el ciclo del empleado</Badge><div className="space-y-5"><h1 className="max-w-3xl text-4xl font-semibold leading-[1.05] tracking-tight text-white sm:text-5xl lg:text-6xl">Contrata, capacita y gestiona a tu equipo desde una sola plataforma.</h1><p className="max-w-2xl text-base leading-8 text-slate-200 sm:text-lg">TalentOS conecta reclutamiento, onboarding, capacitación, inventario y productividad para que tu empresa gestione el ciclo del empleado en un solo lugar.</p></div><div className="flex flex-col gap-3 sm:flex-row"><Button asChild size="lg" className="bg-cyan-400 text-slate-950 shadow-lg shadow-cyan-400/20 hover:bg-cyan-300"><Link href="/register-company">Comenzar ahora <ArrowRight className="size-4" /></Link></Button><Button asChild size="lg" variant="secondary" className="border-white/20 bg-white/10 text-white hover:bg-white/15"><a href="#producto">Explorar plataforma</a></Button></div><p className="text-sm text-slate-300">Configura tu empresa, sucursales y módulos según tus necesidades.</p></div><ProductPreview /></section>; }

function ProductPreview() { const metrics = [["24", "Vacantes activas"], ["86", "Nuevos candidatos"], ["12", "Onboarding pendientes"], ["91%", "Cursos completados"]]; return <div className="relative mx-auto w-full max-w-xl rounded-[2rem] border border-white/15 bg-slate-900/70 p-4 shadow-[0_30px_80px_rgba(1,12,28,.42)] backdrop-blur sm:p-5"><div className="mb-5 flex items-center justify-between"><div><p className="text-xs font-medium uppercase tracking-[.16em] text-cyan-200">Vista ilustrativa</p><h2 className="mt-1 text-xl font-semibold text-white">Tu operación conectada</h2></div><span className="rounded-full bg-emerald-300/15 px-3 py-1 text-xs font-medium text-emerald-100">Todo en un lugar</span></div><div className="grid grid-cols-2 gap-3">{metrics.map(([value, label]) => <div key={label} className="rounded-2xl bg-white/[.07] p-4"><p className="text-2xl font-semibold text-white sm:text-3xl">{value}</p><p className="mt-1 text-xs leading-5 text-slate-300">{label}</p></div>)}</div><div className="mt-4 rounded-2xl border border-white/10 bg-slate-950/35 p-4"><p className="mb-3 text-sm font-medium text-white">Ciclo conectado</p><div className="flex flex-wrap items-center gap-2">{["Vacante", "Candidatos", "Entrevistas", "Onboarding", "Capacitación"].map((step, index) => <span key={step} className="flex items-center gap-2 text-xs text-slate-200"><span className="rounded-full bg-cyan-300/15 px-2.5 py-1">{step}</span>{index < 4 ? <ArrowRight className="size-3 text-cyan-300" /> : null}</span>)}</div></div></div>; }

export function ModulesSection() { return <section id="producto" className="scroll-mt-8 py-10 sm:py-16"><div className="max-w-2xl"><p className="text-sm font-semibold text-primary">Producto</p><h2 className="mt-3 text-3xl font-semibold tracking-tight sm:text-4xl">Todo lo que necesitas para gestionar el ciclo de tu equipo.</h2><p className="mt-4 text-base leading-7 text-muted-foreground">Empieza por los procesos que más importan hoy y conecta los demás cuando tu operación lo necesite.</p></div><div className="mt-10 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{modules.map(({ icon: Icon, title, copy, features }) => <article key={title} className="group rounded-2xl border border-border/70 bg-card p-6 shadow-sm transition duration-200 hover:-translate-y-1 hover:border-primary/35 hover:shadow-lg motion-reduce:transform-none"><span className="flex size-11 items-center justify-center rounded-xl bg-primary/10 text-primary"><Icon className="size-5" /></span><h3 className="mt-5 text-xl font-semibold">{title}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{copy}</p><ul className="mt-5 space-y-2 text-sm text-foreground">{features.map((feature) => <li key={feature} className="flex gap-2"><Check className="mt-0.5 size-4 shrink-0 text-primary" />{feature}</li>)}</ul></article>)}</div></section>; }

export function EmployeeLifecycle() { return <section id="soluciones" className="scroll-mt-8 rounded-[2rem] bg-slate-950 px-5 py-10 text-white sm:px-8 sm:py-14"><div className="max-w-2xl"><p className="text-sm font-semibold text-cyan-300">Flujo integrado</p><h2 className="mt-3 text-3xl font-semibold tracking-tight sm:text-4xl">Del candidato al empleado, sin cambiar de sistema.</h2><p className="mt-4 leading-7 text-slate-300">Cada etapa entrega el contexto necesario a la siguiente para que tu equipo deje de perseguir información entre herramientas.</p></div><ol className="mt-10 grid gap-3 md:grid-cols-4 lg:grid-cols-8">{lifecycle.map((item, index) => <li key={item} className="relative flex items-center gap-3 rounded-xl border border-white/10 bg-white/[.04] p-3 md:block md:min-h-28"><span className="flex size-8 shrink-0 items-center justify-center rounded-full bg-cyan-400 text-xs font-bold text-slate-950">{index + 1}</span><span className="text-sm font-medium md:mt-4 md:block">{item}</span></li>)}</ol></section>; }

export function MultiBranchSection() { return <section className="grid gap-10 py-12 lg:grid-cols-2 lg:items-center"><div><p className="text-sm font-semibold text-primary">Multiempresa y multisucursal</p><h2 className="mt-3 text-3xl font-semibold tracking-tight sm:text-4xl">Crece sin perder el control.</h2><p className="mt-4 max-w-xl leading-7 text-muted-foreground">Administra varias sucursales desde una misma plataforma, manteniendo control y separación de información por empresa.</p><ul className="mt-6 space-y-3 text-sm">{["Usuarios y permisos", "Vacantes y empleados", "Cursos e inventario", "Reportes por alcance"].map((item) => <li key={item} className="flex items-center gap-3"><Check className="size-4 text-primary" />{item}</li>)}</ul></div><div className="rounded-3xl border border-border/70 bg-surface-section p-6"><div className="flex items-center gap-3 font-semibold"><Building2 className="size-5 text-primary" />Empresa principal</div><div className="mt-5 space-y-3 border-l-2 border-primary/25 pl-5">{["Sucursal Miami", "Sucursal Orlando", "Sucursal Tampa"].map((branch) => <div key={branch} className="rounded-xl bg-card p-4 text-sm font-medium shadow-sm">{branch}<p className="mt-1 font-normal text-muted-foreground">Usuarios, operaciones y reportes dentro de su alcance.</p></div>)}</div></div></section>; }

export function FlexibleModulesAndRoles() { const roles = ["Administrador", "Recursos Humanos", "Supervisor", "Instructor", "Empleado", "Candidato"]; return <><section id="planes" className="scroll-mt-8 rounded-3xl border border-border/70 bg-card p-6 sm:p-10"><div className="grid gap-8 lg:grid-cols-2"><div><p className="text-sm font-semibold text-primary">Configuración modular</p><h2 className="mt-3 text-3xl font-semibold tracking-tight">Usa solamente los módulos que tu empresa necesita.</h2><p className="mt-4 leading-7 text-muted-foreground">Cada empresa puede configurar su experiencia según los módulos habilitados en su suscripción.</p></div><ul className="grid gap-3 sm:grid-cols-2">{["Reclutamiento", "Onboarding", "Capacitación", "Inventario", "Productividad"].map((item, index) => <li key={item} className="flex items-center gap-3 rounded-xl bg-surface-section p-4 text-sm font-medium"><span className={`flex size-5 items-center justify-center rounded-md ${index < 3 ? "bg-primary text-primary-foreground" : "border border-border bg-background text-muted-foreground"}`}>{index < 3 ? <Check className="size-3.5" /> : null}</span>{item}</li>)}</ul></div></section><section className="py-12"><div className="text-center"><p className="text-sm font-semibold text-primary">Experiencia por rol</p><h2 className="mt-3 text-3xl font-semibold tracking-tight">Una experiencia diferente para cada usuario.</h2><p className="mx-auto mt-4 max-w-2xl leading-7 text-muted-foreground">Cada persona ve únicamente las herramientas e información necesarias para realizar su trabajo.</p></div><div className="mt-8 grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-6">{roles.map((role) => <div key={role} className="rounded-2xl border border-border/70 bg-card p-4 text-center text-sm font-medium"><Users className="mx-auto mb-3 size-5 text-primary" />{role}</div>)}</div></section></>; }

export function HowItWorks() { return <section id="como-funciona" className="scroll-mt-8 py-10 sm:py-16"><div className="max-w-2xl"><p className="text-sm font-semibold text-primary">Cómo funciona</p><h2 className="mt-3 text-3xl font-semibold tracking-tight sm:text-4xl">Empieza en pocos pasos.</h2></div><ol className="mt-8 grid gap-4 md:grid-cols-4">{["Registra tu empresa.", "Configura sucursales y usuarios.", "Selecciona los módulos que necesitas.", "Empieza a gestionar tu equipo."].map((item, index) => <li key={item} className="rounded-2xl bg-surface-section p-5"><span className="text-sm font-semibold text-primary">0{index + 1}</span><p className="mt-6 font-semibold">{item}</p></li>)}</ol></section>; }

export function CandidateSection() { return <section id="candidatos" className="scroll-mt-8 rounded-3xl bg-cyan-50 p-6 sm:p-10"><div className="grid gap-6 md:grid-cols-[1fr_auto] md:items-center"><div><p className="text-sm font-semibold text-cyan-800">Portal de candidatos</p><h2 className="mt-3 text-3xl font-semibold tracking-tight text-slate-950">¿Buscas empleo?</h2><p className="mt-3 max-w-2xl leading-7 text-slate-700">Explora vacantes disponibles y consulta el estado de tus postulaciones.</p></div><div className="flex flex-col gap-3 sm:flex-row"><Button asChild><Link href="/jobs">Ver empleos</Link></Button><Button asChild variant="secondary"><Link href="/application-status">Seguir mi postulación</Link></Button></div></div></section>; }

export function FinalCTA() { return <section className="rounded-[2rem] bg-[linear-gradient(135deg,#063c5d,#0e7490)] px-6 py-12 text-white sm:px-10"><div className="max-w-3xl"><p className="text-sm font-semibold text-cyan-100">TalentOS</p><h2 className="mt-3 text-3xl font-semibold tracking-tight sm:text-4xl">Centraliza la gestión de tu equipo con TalentOS.</h2><p className="mt-4 leading-7 text-cyan-50/85">Reclutamiento, incorporación, capacitación e inventario trabajando juntos.</p><div className="mt-7 flex flex-col gap-3 sm:flex-row"><Button asChild size="lg" className="bg-white text-slate-950 hover:bg-cyan-50"><Link href="/register-company">Registrar empresa</Link></Button><Button asChild size="lg" variant="secondary" className="border-white/25 bg-transparent text-white hover:bg-white/10"><Link href="/login">Iniciar sesión</Link></Button></div></div></section>; }

export function LandingFooter() { return <footer className="grid gap-8 border-t border-border/70 py-10 sm:grid-cols-2 lg:grid-cols-[1.5fr_repeat(3,1fr)]"><div><p className="text-lg font-semibold">TalentOS</p><p className="mt-3 max-w-xs text-sm leading-6 text-muted-foreground">Gestión de equipos desde reclutamiento hasta operación.</p></div><FooterColumn title="Producto" links={[["Reclutamiento", "#producto"], ["Onboarding", "#producto"], ["Capacitación", "#producto"], ["Inventario", "#producto"], ["Productividad", "#producto"]]} /><FooterColumn title="Recursos" links={[["Empleos", "/jobs"], ["Seguir postulación", "/application-status"], ["Iniciar sesión", "/login"]]} /><FooterColumn title="Empresa" links={[["Registrar empresa", "/register-company"], ["Módulos", "#planes"], ["Cómo funciona", "#como-funciona"]]} /><p className="text-xs text-muted-foreground sm:col-span-2 lg:col-span-4">© {new Date().getFullYear()} TalentOS. Plataforma SaaS para la gestión de equipos.</p></footer>; }
function FooterColumn({ title, links }: { title: string; links: string[][] }) { return <div><p className="text-sm font-semibold">{title}</p><ul className="mt-3 space-y-2">{links.map(([label, href]) => <li key={label}><Link href={href} className="text-sm text-muted-foreground hover:text-primary">{label}</Link></li>)}</ul></div>; }
