"use client";

import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { BookOpenCheck, Gavel, Plus, ShieldCheck } from "lucide-react";
import { toast } from "sonner";
import { approveOnboardingRetentionPolicy, createOnboardingLibraryItem, exportOnboardingDossier, fetchOnboardingFlows, fetchOnboardingLibrary, fetchOnboardingRetentionPolicies, fetchOnboardingSignatureEvidence, getApiErrorMessage, placeOnboardingLegalHold, saveOnboardingRetentionPolicy } from "@/lib/backend";
import { useAppStore } from "@/store/app-store";
import { PageHeader } from "@/components/design-system";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";

export default function OnboardingCompliancePage() {
  const queryClient = useQueryClient();
  const { can } = useAppStore();
  const [countryCode, setCountryCode] = useState("US");
  const [library, setLibrary] = useState({ type: "TASK" as "TASK" | "DOCUMENT" | "POLICY", name: "", description: "" });
  const [retention, setRetention] = useState({ countryCode: "US", documentCategory: "CONTRATO", retentionDays: "2555", legalBasis: "" });
  const [flowId, setFlowId] = useState("");
  const [holdReason, setHoldReason] = useState("");
  const libraryQuery = useQuery({ queryKey: ["onboarding-library"], queryFn: fetchOnboardingLibrary });
  const policiesQuery = useQuery({ queryKey: ["onboarding-retention-policies"], queryFn: fetchOnboardingRetentionPolicies });
  const evidenceQuery = useQuery({ queryKey: ["onboarding-signature-evidence", countryCode], queryFn: () => fetchOnboardingSignatureEvidence(countryCode) });
  const flowsQuery = useQuery({ queryKey: ["onboarding-compliance-flows"], queryFn: () => fetchOnboardingFlows({ page: 1, pageSize: 100 }) });
  const addLibrary = useMutation({ mutationFn: () => createOnboardingLibraryItem({ ...library, description: library.description || undefined }), onSuccess: async () => { setLibrary({ type: "TASK", name: "", description: "" }); await queryClient.invalidateQueries({ queryKey: ["onboarding-library"] }); toast.success("Elemento agregado a la biblioteca"); }, onError: (error) => toast.error(getApiErrorMessage(error, "No fue posible guardar el elemento.")) });
  const savePolicy = useMutation({ mutationFn: () => saveOnboardingRetentionPolicy({ ...retention, retentionDays: Number(retention.retentionDays), legalBasis: retention.legalBasis || undefined }), onSuccess: async () => { await queryClient.invalidateQueries({ queryKey: ["onboarding-retention-policies"] }); toast.success("Regla de retención guardada"); }, onError: (error) => toast.error(getApiErrorMessage(error, "No fue posible guardar la regla.")) });
  const approvePolicy = useMutation({ mutationFn: (id: string) => approveOnboardingRetentionPolicy(id), onSuccess: async () => { await queryClient.invalidateQueries({ queryKey: ["onboarding-retention-policies"] }); toast.success("Revisión jurídica registrada. La regla ya puede ejecutarse."); }, onError: (error) => toast.error(getApiErrorMessage(error, "No fue posible aprobar la regla. La persona revisora debe ser distinta de quien la creó.")) });
  const placeHold = useMutation({ mutationFn: () => placeOnboardingLegalHold(flowId, { reason: holdReason }), onSuccess: () => { setHoldReason(""); toast.success("Legal hold aplicado; la eliminación documental queda bloqueada."); }, onError: (error) => toast.error(getApiErrorMessage(error, "No fue posible aplicar el legal hold.")) });
  const downloadDossier = useMutation({ mutationFn: () => exportOnboardingDossier(flowId), onSuccess: (dossier) => { const url = URL.createObjectURL(new Blob([JSON.stringify(dossier, null, 2)], { type: "application/json" })); const link = document.createElement("a"); link.href = url; link.download = `expediente-incorporacion-${flowId}.json`; link.click(); URL.revokeObjectURL(url); toast.success("Expediente exportado"); }, onError: (error) => toast.error(getApiErrorMessage(error, "No fue posible exportar el expediente.")) });

  return <div className="space-y-7">
    <PageHeader eyebrow="Personas" title="Cumplimiento de incorporación" description="Gobierna contenido reutilizable, conservación de expedientes y evidencia de firma por país." />
    <section className="grid gap-5 xl:grid-cols-2">
      <Card><CardHeader><CardTitle className="flex items-center gap-2"><BookOpenCheck className="size-5 text-brand" />Biblioteca reutilizable</CardTitle></CardHeader><CardContent className="space-y-4"><p className="text-sm text-muted-foreground">Tareas, documentos y políticas disponibles para diseñar nuevas versiones de plantillas.</p>{can("onboarding.manage") ? <div className="grid gap-3 sm:grid-cols-2"><div><Label>Tipo</Label><Select value={library.type} onValueChange={(type) => setLibrary({ ...library, type: type as typeof library.type })}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="TASK">Tarea</SelectItem><SelectItem value="DOCUMENT">Documento</SelectItem><SelectItem value="POLICY">Política</SelectItem></SelectContent></Select></div><div><Label htmlFor="library-name">Nombre</Label><Input id="library-name" value={library.name} onChange={(event) => setLibrary({ ...library, name: event.target.value })} /></div><div className="sm:col-span-2"><Label htmlFor="library-description">Descripción</Label><Input id="library-description" value={library.description} onChange={(event) => setLibrary({ ...library, description: event.target.value })} /></div><Button className="sm:col-span-2" disabled={!library.name.trim() || addLibrary.isPending} onClick={() => addLibrary.mutate()}><Plus className="size-4" />Agregar a biblioteca</Button></div> : null}<div className="space-y-2">{libraryQuery.data?.map((item) => <div key={item.id} className="flex items-center justify-between rounded-xl border p-3"><div><p className="font-medium">{item.name}</p><p className="text-xs text-muted-foreground">{item.description || "Sin descripción"}</p></div><Badge variant="secondary">{item.type}</Badge></div>)}</div></CardContent></Card>
      <Card><CardHeader><CardTitle className="flex items-center gap-2"><Gavel className="size-5 text-brand" />Retención y legal hold</CardTitle></CardHeader><CardContent className="space-y-4"><p className="text-sm text-muted-foreground">Las reglas definen conservación mínima. Un legal hold activo bloquea la eliminación de documentos del expediente. La aprobación registra una revisión operativa por país, pero no sustituye el criterio de asesoría jurídica local.</p>{can("onboarding.manage") ? <div className="grid gap-3 sm:grid-cols-2"><div><Label htmlFor="retention-country">País</Label><Input id="retention-country" maxLength={8} value={retention.countryCode} onChange={(event) => setRetention({ ...retention, countryCode: event.target.value.toUpperCase() })} /></div><div><Label htmlFor="retention-category">Categoría</Label><Input id="retention-category" value={retention.documentCategory} onChange={(event) => setRetention({ ...retention, documentCategory: event.target.value })} /></div><div><Label htmlFor="retention-days">Días de retención</Label><Input id="retention-days" type="number" min="1" value={retention.retentionDays} onChange={(event) => setRetention({ ...retention, retentionDays: event.target.value })} /></div><div><Label htmlFor="retention-basis">Base legal</Label><Input id="retention-basis" value={retention.legalBasis} onChange={(event) => setRetention({ ...retention, legalBasis: event.target.value })} /></div><Button className="sm:col-span-2" disabled={!retention.countryCode || !retention.documentCategory || Number(retention.retentionDays) < 1 || savePolicy.isPending} onClick={() => savePolicy.mutate()}><ShieldCheck className="size-4" />Guardar regla</Button></div> : null}<div className="space-y-2">{policiesQuery.data?.map((policy) => <div key={policy.id} className="rounded-xl border p-3"><div className="flex flex-wrap items-center justify-between gap-2"><p className="font-medium">{policy.countryCode} · {policy.documentCategory}</p><span className={policy.legalReviewStatus === "APPROVED" ? "rounded-full bg-emerald-100 px-2 py-1 text-xs font-medium text-emerald-800" : "rounded-full bg-amber-100 px-2 py-1 text-xs font-medium text-amber-800"}>{policy.legalReviewStatus === "APPROVED" ? "Revisión aprobada" : "Pendiente de revisión"}</span></div><p className="text-xs text-muted-foreground">{policy.retentionDays} días{policy.legalBasis ? ` · ${policy.legalBasis}` : ""}</p>{can("onboarding.manage") && policy.legalReviewStatus !== "APPROVED" ? <Button className="mt-3" size="sm" variant="outline" disabled={approvePolicy.isPending} onClick={() => approvePolicy.mutate(policy.id)}>Registrar revisión local</Button> : null}</div>)}</div></CardContent></Card>
    </section>
    <Card><CardHeader><CardTitle>Perfil de evidencia para firma electrónica</CardTitle></CardHeader><CardContent className="space-y-4"><div className="max-w-xs"><Label htmlFor="evidence-country">País</Label><Input id="evidence-country" maxLength={8} value={countryCode} onChange={(event) => setCountryCode(event.target.value.toUpperCase())} /></div>{evidenceQuery.data ? <div className="rounded-xl bg-muted/50 p-4"><p className="font-medium">{evidenceQuery.data.framework}</p><div className="mt-3 flex flex-wrap gap-2">{evidenceQuery.data.evidence.map((item) => <Badge key={item} variant="secondary">{item}</Badge>)}</div><p className="mt-3 text-xs text-muted-foreground">{evidenceQuery.data.disclaimer}</p></div> : null}</CardContent></Card>
    {can("onboarding.manage") ? <Card><CardHeader><CardTitle>Control del expediente</CardTitle></CardHeader><CardContent className="grid gap-3 md:grid-cols-2"><div className="space-y-2"><Label>Expediente</Label><Select value={flowId} onValueChange={setFlowId}><SelectTrigger><SelectValue placeholder="Selecciona una incorporación" /></SelectTrigger><SelectContent>{flowsQuery.data?.items.map((flow) => <SelectItem key={flow.id} value={flow.id}>{flow.employee.name} · {flow.branch.name}</SelectItem>)}</SelectContent></Select></div><div className="space-y-2"><Label htmlFor="legal-hold-reason">Motivo del legal hold</Label><Input id="legal-hold-reason" value={holdReason} onChange={(event) => setHoldReason(event.target.value)} placeholder="Litigio, auditoría o investigación" /></div><div className="flex flex-wrap gap-2 md:col-span-2"><Button variant="secondary" disabled={!flowId || downloadDossier.isPending} onClick={() => downloadDossier.mutate()}>Exportar expediente completo</Button><Button variant="destructive" disabled={!flowId || !holdReason.trim() || placeHold.isPending} onClick={() => placeHold.mutate()}>Aplicar legal hold</Button></div></CardContent></Card> : null}
  </div>;
}
