"use client";

import { useEffect, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Inbox, MailCheck, RefreshCw, Reply } from "lucide-react";
import { configureCommunicationDomain, fetchCommunicationDomain, fetchCommunicationInbox, replyCandidateEmail, verifyCommunicationDomain } from "@/lib/backend";
import type { AtsMessageDto } from "@/lib/contracts";
import { InlineFeedback, Pagination } from "@/components/design-system";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";

export function CommunicationOperationsConsole() {
  const queryClient = useQueryClient();
  const [page, setPage] = useState(1);
  const [search, setSearch] = useState("");
  const [replying, setReplying] = useState<AtsMessageDto | null>(null);
  const [replyBody, setReplyBody] = useState("");
  const [domainForm, setDomainForm] = useState({ domain: "", fromName: "Talentos", fromEmail: "", replyToEmail: "", dkimSelector: "resend" });
  const domain = useQuery({ queryKey: ["communication-domain"], queryFn: fetchCommunicationDomain });
  const inbox = useQuery({ queryKey: ["communication-inbox", page, search], queryFn: () => fetchCommunicationInbox({ page, pageSize: 20, search: search || undefined }) });
  useEffect(() => { if (domain.data) setDomainForm({ domain: domain.data.domain, fromName: domain.data.fromName, fromEmail: domain.data.fromEmail, replyToEmail: domain.data.replyToEmail ?? "", dkimSelector: domain.data.dkimSelector }); }, [domain.data]);
  const saveDomain = useMutation({ mutationFn: () => configureCommunicationDomain({ ...domainForm, replyToEmail: domainForm.replyToEmail || undefined }), onSuccess: async () => queryClient.invalidateQueries({ queryKey: ["communication-domain"] }) });
  const verify = useMutation({ mutationFn: verifyCommunicationDomain, onSuccess: async () => queryClient.invalidateQueries({ queryKey: ["communication-domain"] }) });
  const sendReply = useMutation({ mutationFn: () => replyCandidateEmail(replying!.id, { subject: `Re: ${replying!.subject}`, body: replyBody }), onSuccess: async () => { setReplying(null); setReplyBody(""); await queryClient.invalidateQueries({ queryKey: ["communication-inbox"] }); } });
  const metrics = inbox.data?.data.flatMap((message) => message.notification?.deliveries ?? []) ?? [];

  return <section className="space-y-5"><div className="grid gap-5 xl:grid-cols-[.8fr_1.2fr]">
    <Card level={2}><CardHeader><CardTitle><span className="inline-flex items-center gap-2"><MailCheck className="size-5" />Dominio y entregabilidad</span></CardTitle></CardHeader><CardContent className="space-y-4"><div className="grid gap-3 sm:grid-cols-2"><Input placeholder="dominio.com" value={domainForm.domain} onChange={(event) => setDomainForm({ ...domainForm, domain: event.target.value })} /><Input placeholder="Nombre remitente" value={domainForm.fromName} onChange={(event) => setDomainForm({ ...domainForm, fromName: event.target.value })} /><Input type="email" placeholder="talento@dominio.com" value={domainForm.fromEmail} onChange={(event) => setDomainForm({ ...domainForm, fromEmail: event.target.value })} /><Input type="email" placeholder="respuestas@dominio.com" value={domainForm.replyToEmail} onChange={(event) => setDomainForm({ ...domainForm, replyToEmail: event.target.value })} /></div><div className="flex flex-wrap gap-2"><Button onClick={() => saveDomain.mutate()} disabled={!domainForm.domain || !domainForm.fromEmail || saveDomain.isPending}>Guardar dominio</Button><Button variant="secondary" onClick={() => verify.mutate()} disabled={!domain.data || verify.isPending}><RefreshCw className="size-4" />Verificar DNS</Button></div>{domain.data ? <><div className="flex flex-wrap gap-2"><Badge variant={domain.data.spfVerified ? "default" : "secondary"}>SPF {domain.data.spfVerified ? "correcto" : "pendiente"}</Badge><Badge variant={domain.data.dkimVerified ? "default" : "secondary"}>DKIM {domain.data.dkimVerified ? "correcto" : "pendiente"}</Badge><Badge variant={domain.data.dmarcVerified ? "default" : "secondary"}>DMARC {domain.data.dmarcVerified ? "correcto" : "pendiente"}</Badge></div><dl className="grid grid-cols-2 gap-3 text-sm"><Metric label="Reputación" value={domain.data.reputationScore} /><Metric label="Entrega" value={domain.data.deliveryRate} suffix="%" /><Metric label="Rebote" value={domain.data.bounceRate} suffix="%" /><Metric label="Quejas" value={domain.data.complaintRate} suffix="%" /></dl></> : <InlineFeedback tone="warning" title="Dominio pendiente">Configura SPF, DKIM y DMARC antes de usar el dominio como remitente.</InlineFeedback>}</CardContent></Card>
    <Card level={2}><CardHeader><CardTitle><span className="inline-flex items-center gap-2"><Inbox className="size-5" />Bandeja bidireccional</span></CardTitle></CardHeader><CardContent className="space-y-4"><Input placeholder="Buscar candidato, asunto o contenido" value={search} onChange={(event) => { setSearch(event.target.value); setPage(1); }} /><div className="grid grid-cols-4 gap-2 text-center text-xs"><Metric label="Entregados" value={metrics.filter((item) => item.deliveredAt).length} /><Metric label="Abiertos" value={metrics.filter((item) => item.openedAt).length} /><Metric label="Rebotes" value={metrics.filter((item) => item.bouncedAt).length} /><Metric label="Quejas" value={metrics.filter((item) => item.complainedAt).length} /></div><div className="max-h-[520px] space-y-3 overflow-y-auto">{inbox.data?.data.map((message) => <article key={message.id} className={`rounded-xl border p-3 ${message.direction === "INBOUND" ? "border-primary/40 bg-primary/5" : ""}`}><div className="flex flex-wrap justify-between gap-2"><div><p className="font-medium">{message.subject}</p><p className="text-xs text-text-secondary">{message.direction === "INBOUND" ? message.senderEmail : message.recipientEmail} · {new Date(message.createdAt).toLocaleString()}</p></div><Badge variant={message.direction === "INBOUND" ? "default" : "secondary"}>{message.direction === "INBOUND" ? "Recibido" : message.status}</Badge></div><p className="mt-2 line-clamp-3 whitespace-pre-wrap text-sm">{message.body}</p>{message.direction === "INBOUND" ? <Button className="mt-3" size="sm" variant="secondary" onClick={() => setReplying(message)}><Reply className="size-4" />Responder</Button> : null}</article>)}</div>{inbox.data?.meta.totalPages ? <Pagination page={inbox.data.meta.page - 1} totalPages={inbox.data.meta.totalPages} totalItems={inbox.data.meta.total} pageSize={inbox.data.meta.pageSize} onPageChange={(next) => setPage(next + 1)} /> : null}</CardContent></Card>
  </div>{replying ? <Card level={1}><CardHeader><CardTitle>Responder a {replying.senderEmail}</CardTitle></CardHeader><CardContent className="space-y-3"><textarea className="w-full rounded-xl border bg-background p-3" rows={6} value={replyBody} onChange={(event) => setReplyBody(event.target.value)} /><div className="flex gap-2"><Button onClick={() => sendReply.mutate()} disabled={replyBody.trim().length < 2 || sendReply.isPending}>Enviar correo</Button><Button variant="ghost" onClick={() => setReplying(null)}>Cancelar</Button></div></CardContent></Card> : null}</section>;
}

function Metric({ label, value, suffix = "" }: { label: string; value?: number | string | null; suffix?: string }) { return <div className="rounded-xl bg-surface-section p-2"><dt className="text-text-secondary">{label}</dt><dd className="font-semibold">{value == null ? "N/D" : `${Number(value).toFixed(typeof value === "number" && Number.isInteger(value) ? 0 : 1)}${suffix}`}</dd></div>; }
