"use client";

import Link from "next/link";
import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { AlertTriangle, ArrowLeft, BriefcaseBusiness, CheckCircle2, Clock3, Download, FileCheck2, FileText, MapPin, Pencil, ShieldCheck, Upload, UserRound, WalletCards } from "lucide-react";
import { AsyncState } from "@/components/async-state";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { InlineFeedback, PageHeader } from "@/components/design-system";
import { downloadOnboardingDocument, fetchEmployeeDetail, fetchEmployeePayrollCompliance, fetchOnboardingFlows, getApiErrorMessage, reviewOnboardingDocument, uploadOnboardingDocument } from "@/lib/backend";
import type { EmployeeOnboardingDocumentDto, EmployeeOnboardingFlowDto } from "@/lib/contracts";
import type { EmployeePayrollComplianceSnapshot } from "@/lib/backend";
import { useAppStore } from "@/store/app-store";

export function Employee360Page({ employeeId }: { employeeId: string }) {
  const { can } = useAppStore();
  const queryClient = useQueryClient();
  const [uploadOpen, setUploadOpen] = useState(false);
  const [uploadError, setUploadError] = useState<string | null>(null);
  const dossier = useQuery({ queryKey: ["employee-360", employeeId], queryFn: () => fetchEmployeeDetail(employeeId) });
  const payrollCompliance = useQuery({ queryKey: ["employee-payroll-compliance", employeeId], queryFn: () => fetchEmployeePayrollCompliance(employeeId), enabled: can("employees.read") });
  const onboarding = useQuery({ queryKey: ["employee-360-onboarding", employeeId], queryFn: () => fetchOnboardingFlows({ page: 1, pageSize: 100 }), enabled: can("onboarding.view") });
  const flow = onboarding.data?.items.find((item) => item.employee.id === employeeId) ?? null;
  const refreshOnboarding = () => void queryClient.invalidateQueries({ queryKey: ["employee-360-onboarding", employeeId] });
  const reviewDocument = useMutation({ mutationFn: (id: string) => reviewOnboardingDocument(id, "APPROVED"), onSuccess: refreshOnboarding });
  const uploadDocument = useMutation({
    mutationFn: ({ file, category }: { file: File; category: string }) => uploadOnboardingDocument(flow!.id, { file, category }),
    onSuccess: () => { setUploadOpen(false); setUploadError(null); refreshOnboarding(); },
    onError: (error) => setUploadError(getApiErrorMessage(error, "No fue posible cargar el documento.")),
  });

  if (dossier.isLoading) return <AsyncState state="loading" title="Cargando expediente" description="Preparamos la información laboral y la trazabilidad del empleado." />;
  if (dossier.isError || !dossier.data) return <AsyncState state="error" title="No fue posible cargar el expediente" description={getApiErrorMessage(dossier.error, "El expediente no está disponible en este contexto.")} onRetry={() => void dossier.refetch()} />;

  const { employee, documents, history } = dossier.data;
  const primary = employee.branchAssignments.find((assignment) => assignment.isPrimary) ?? employee.branchAssignments[0];
  return <div className="space-y-6">
    <PageHeader eyebrow="Personas / Empleados" title={employee.name} description={<span className="flex flex-wrap gap-x-3 gap-y-1"><span>{employee.jobTitle ?? primary?.role ?? "Cargo sin definir"}</span><span>{primary?.branch.name ?? "Sucursal sin asignar"}</span></span>} actions={<><Button asChild variant="secondary"><Link href="/employees"><ArrowLeft className="size-4" />Directorio</Link></Button>{can("employees.update") ? <Button asChild><Link href={`/employees/${employeeId}/edit`}><Pencil className="size-4" />Editar</Link></Button> : null}</>} />
    <Card level={2}><CardContent className="flex flex-col gap-5 p-5 sm:flex-row sm:items-center sm:justify-between sm:p-6"><div className="flex min-w-0 items-center gap-4"><div className="flex size-14 shrink-0 items-center justify-center rounded-2xl bg-primary/10 text-xl font-semibold text-primary">{initials(employee.name)}</div><div className="min-w-0"><p className="truncate text-xl font-semibold">{employee.name}</p><p className="mt-1 truncate text-sm text-text-secondary">{employee.email}</p><div className="mt-3 flex flex-wrap gap-2"><Badge variant={employee.status === "ACTIVE" ? "success" : "secondary"}>{statusLabel(employee.status)}</Badge>{primary ? <Badge variant="outline"><MapPin className="mr-1 size-3.5" />{primary.branch.name}</Badge> : null}</div></div></div><div className="grid grid-cols-2 gap-3 sm:min-w-64"><Metric label="Documentos" value={String(flow?.documents.length ?? employee.documentSummary?.totalDocuments ?? 0)} /><Metric label="Asignaciones" value={String(employee.branchAssignments.length)} /></div></CardContent></Card>
    <Tabs defaultValue="overview" className="space-y-5"><div className="overflow-x-auto pb-1"><TabsList className="min-w-max"><TabsTrigger value="overview">Resumen</TabsTrigger><TabsTrigger value="employment">Empleo</TabsTrigger>{can("employees.read") ? <TabsTrigger value="payroll">Nómina</TabsTrigger> : null}{can("employees.read") ? <TabsTrigger value="tax">Impuestos y elegibilidad</TabsTrigger> : null}<TabsTrigger value="documents">Documentos</TabsTrigger><TabsTrigger value="compliance">Cumplimiento</TabsTrigger><TabsTrigger value="history">Historial</TabsTrigger>{can("employees.read") ? <TabsTrigger value="audit">Auditoría</TabsTrigger> : null}</TabsList></div>
      <TabsContent value="overview"><Overview employee={employee} documents={flow?.documents.length ?? documents.length} flow={flow} /></TabsContent>
      <TabsContent value="employment"><Employment employee={employee} /></TabsContent>
      {can("employees.read") ? <TabsContent value="payroll"><Payroll snapshot={payrollCompliance.data} isLoading={payrollCompliance.isLoading} error={payrollCompliance.error} onRetry={() => void payrollCompliance.refetch()} /></TabsContent> : null}
      {can("employees.read") ? <TabsContent value="tax"><TaxEligibility snapshot={payrollCompliance.data} isLoading={payrollCompliance.isLoading} error={payrollCompliance.error} onRetry={() => void payrollCompliance.refetch()} /></TabsContent> : null}
      <TabsContent value="documents"><Documents flow={flow} isLoading={onboarding.isLoading} canManage={can("onboarding.manage")} canView={can("onboarding.view")} approving={reviewDocument.isPending} onApprove={(id) => reviewDocument.mutate(id)} onDownload={downloadDocument} onUpload={() => { setUploadError(null); setUploadOpen(true); }} /></TabsContent>
      <TabsContent value="compliance"><Compliance flow={flow} isLoading={onboarding.isLoading} canView={can("onboarding.view")} /></TabsContent>
      <TabsContent value="history"><History events={history} /></TabsContent>
      {can("employees.read") ? <TabsContent value="audit"><Audit snapshot={payrollCompliance.data} isLoading={payrollCompliance.isLoading} error={payrollCompliance.error} onRetry={() => void payrollCompliance.refetch()} /></TabsContent> : null}
    </Tabs>
    <Dialog open={uploadOpen} onOpenChange={setUploadOpen}><DialogContent><DialogHeader><DialogTitle>Cargar documento</DialogTitle><DialogDescription>El archivo se guardará en el flujo de incorporación de este empleado.</DialogDescription></DialogHeader><form className="mt-5 space-y-4" onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); const file = form.get("file"); if (!(file instanceof File) || !file.size) { setUploadError("Selecciona un archivo para continuar."); return; } uploadDocument.mutate({ file, category: String(form.get("category") ?? "OTHER") }); }}><label className="block space-y-2 text-sm font-medium">Categoría<select name="category" className="flex h-11 w-full rounded-xl border border-border-default bg-card px-3 text-sm"><option value="OTHER">Otro documento</option><option value="IDENTITY">Identidad</option><option value="CONTRACT">Contrato</option><option value="CERTIFICATE">Certificado</option></select></label><label className="block space-y-2 text-sm font-medium">Archivo<input name="file" type="file" className="block w-full text-sm text-text-secondary file:mr-3 file:rounded-lg file:border-0 file:bg-surface-section file:px-3 file:py-2 file:font-medium" /></label>{uploadError ? <InlineFeedback tone="danger" title="No se pudo cargar">{uploadError}</InlineFeedback> : null}<div className="flex justify-end gap-3"><Button type="button" variant="secondary" onClick={() => setUploadOpen(false)}>Cancelar</Button><Button type="submit" disabled={uploadDocument.isPending}><Upload className="size-4" />{uploadDocument.isPending ? "Cargando..." : "Cargar documento"}</Button></div></form></DialogContent></Dialog>
  </div>;
}

function Overview({ employee, documents, flow }: { employee: Awaited<ReturnType<typeof fetchEmployeeDetail>>["employee"]; documents: number; flow: EmployeeOnboardingFlowDto | null }) { const primary = employee.branchAssignments.find((assignment) => assignment.isPrimary) ?? employee.branchAssignments[0]; const source = "recordSource" in employee ? employee.recordSource : undefined; return <div className="grid gap-5 lg:grid-cols-[1.15fr_0.85fr]"><Card level={2}><CardContent className="p-5"><SectionTitle icon={<UserRound className="size-4" />} title="Información básica" /><dl className="mt-4 grid gap-4 sm:grid-cols-2"><Datum label="ID de empleado" value={employee.id} /><Datum label="Correo" value={employee.email} /><Datum label="Estado" value={statusLabel(employee.status)} /><Datum label="Origen" value={source === "CANDIDATE_CONVERSION" ? "Conversión de candidato" : "Directorio"} /></dl></CardContent></Card><div className="space-y-5"><Card level={2}><CardContent className="p-5"><SectionTitle icon={<BriefcaseBusiness className="size-4" />} title="Relación laboral" /><dl className="mt-4 grid gap-4"><Datum label="Cargo" value={employee.jobTitle ?? primary?.role ?? "Sin definir"} /><Datum label="Sucursal" value={primary?.branch.name ?? "Sin asignar"} /></dl></CardContent></Card><Card level={2}><CardContent className="p-5"><SectionTitle icon={<FileText className="size-4" />} title="Documentos" /><p className="mt-3 text-3xl font-semibold">{documents}</p><p className="mt-1 text-sm text-text-secondary">documentos en el expediente</p></CardContent></Card></div>{flow ? <InlineFeedback tone="info" title="Incorporación en curso">{flow.progressPercent}% completado. Consulta documentos y cumplimiento para revisar el avance real.</InlineFeedback> : <InlineFeedback tone="info" title="Sin flujo de incorporación">Aún no hay tareas ni documentos de incorporación asociados a este empleado.</InlineFeedback>}</div>; }
function Employment({ employee }: { employee: Awaited<ReturnType<typeof fetchEmployeeDetail>>["employee"] }) { return <div className="space-y-5"><Card level={2}><CardContent className="p-5"><SectionTitle icon={<BriefcaseBusiness className="size-4" />} title="Asignaciones activas" /><div className="mt-4 divide-y divide-border-default">{employee.branchAssignments.length ? employee.branchAssignments.map((assignment) => <div key={assignment.id} className="flex flex-col gap-2 py-4 first:pt-0 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-medium">{assignment.branch.name}</p><p className="text-sm text-text-secondary">{assignment.role}</p></div><Badge variant={assignment.isPrimary ? "success" : "secondary"}>{assignment.isPrimary ? "Principal" : "Secundaria"}</Badge></div>) : <p className="text-sm text-text-secondary">No hay una sucursal asignada.</p>}</div></CardContent></Card></div>; }
function Payroll({ snapshot, isLoading, error, onRetry }: SnapshotSectionProps) { if (isLoading) return <AsyncState state="loading" title="Cargando nómina" description="Consultamos la configuración de nómina autorizada." />; if (error) return <AsyncState state="error" title="No fue posible cargar nómina" description={getApiErrorMessage(error, "No tienes permiso para consultar esta sección del expediente.")} onRetry={onRetry} />; if (!snapshot) return null; const payroll = snapshot.payroll; const configured = Boolean(payroll.payType || payroll.payrollProvider || payroll.payrollEmployeeId); return <div className="space-y-5"><Card level={2}><CardContent className="p-5"><SectionTitle icon={<WalletCards className="size-4" />} title="Configuración de nómina" />{configured ? <dl className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><Datum label="Tipo de pago" value={payroll.payType ?? "Sin configurar"} /><Datum label="Frecuencia" value={payroll.payFrequency ?? "Sin configurar"} /><Datum label="Elegible para horas extra" value={booleanLabel(payroll.overtimeEligible)} /><Datum label="Semana laboral" value={payroll.workweekStartDay ?? "Sin configurar"} /><Datum label="Proveedor" value={payroll.payrollProvider ?? "Sin configurar"} /><Datum label="ID de nómina" value={payroll.payrollEmployeeId ?? "Sin configurar"} /></dl> : <EmptyState title="Nómina aún no configurada" description="El expediente está preparado para enlazar una integración de nómina, pero el proveedor aún no ha registrado datos para este empleado." />}</CardContent></Card><InlineFeedback tone="info" title="Información protegida">Las tasas de pago y referencias externas no se solicitan ni se muestran hasta que el backend publique permisos y operaciones específicas de compensación.</InlineFeedback></div>; }
function TaxEligibility({ snapshot, isLoading, error, onRetry }: SnapshotSectionProps) { if (isLoading) return <AsyncState state="loading" title="Cargando impuestos y elegibilidad" />; if (error) return <AsyncState state="error" title="No fue posible cargar impuestos y elegibilidad" description={getApiErrorMessage(error, "No tienes permiso para consultar esta sección del expediente.")} onRetry={onRetry} />; if (!snapshot) return null; const items = [{ label: "SSN", status: snapshot.tax.ssnMasked ? "Registrado" : "No registrado", detail: snapshot.tax.ssnMasked ?? "No se ha registrado un identificador fiscal visible." }, { label: "W-4", status: snapshot.tax.w4Status, detail: snapshot.tax.w4CompletedAt ? `Actualizado ${formatDate(snapshot.tax.w4CompletedAt)}` : "Sin documento asociado" }, { label: "I-9", status: snapshot.i9.status, detail: snapshot.i9.verificationCompletedAt ? `Verificado ${formatDate(snapshot.i9.verificationCompletedAt)}` : "Sin verificación registrada" }, { label: "E-Verify", status: snapshot.eVerify.status, detail: snapshot.eVerify.required ? (snapshot.eVerify.completedAt ? `Completado ${formatDate(snapshot.eVerify.completedAt)}` : "Requerido por la política aplicable") : "No requerido" }, { label: "Florida New Hire", status: snapshot.floridaNewHire.status, detail: snapshot.floridaNewHire.required ? (snapshot.floridaNewHire.dueDate ? `Vence ${formatDate(snapshot.floridaNewHire.dueDate)}` : "Pendiente de reporte") : "No requerido" }]; return <div className="space-y-5"><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{items.map((item) => <Card key={item.label} level={2}><CardContent className="p-5"><p className="font-semibold">{item.label}</p><div className="mt-3"><ComplianceBadge status={item.status} /></div><p className="mt-3 text-sm text-text-secondary">{item.detail}</p></CardContent></Card>)}</div><InlineFeedback tone="info" title="Datos fiscales protegidos">El expediente solo muestra valores enmascarados. Las configuraciones y documentos sensibles se gestionan mediante permisos y endpoints específicos.</InlineFeedback></div>; }
function Audit({ snapshot, isLoading, error, onRetry }: SnapshotSectionProps) { if (isLoading) return <AsyncState state="loading" title="Cargando auditoría" />; if (error) return <AsyncState state="error" title="No fue posible cargar auditoría" description={getApiErrorMessage(error, "No tienes permiso para consultar esta sección del expediente.")} onRetry={onRetry} />; if (!snapshot) return null; return <div className="space-y-5">{snapshot.alerts.length ? <InlineFeedback tone="warning" title="Alertas del expediente">{snapshot.alerts.map((alert) => alert.message).join(" · ")}</InlineFeedback> : null}<Card level={2}><CardContent className="p-5"><SectionTitle icon={<Clock3 className="size-4" />} title="Trazabilidad del expediente" /><div className="mt-4 divide-y divide-border-default">{snapshot.auditTrail.length ? snapshot.auditTrail.map((event) => <div key={event.id} className="flex flex-col gap-1 py-4 first:pt-0 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-medium">{event.action}</p><p className="text-sm text-text-secondary">{event.actorEmail ?? event.actorRole ?? "Sistema"}</p></div><time className="text-xs text-text-secondary">{formatDate(event.createdAt)}</time></div>) : <p className="text-sm text-text-secondary">No hay eventos auditables disponibles.</p>}</div></CardContent></Card></div>; }
type SnapshotSectionProps = { snapshot?: EmployeePayrollComplianceSnapshot; isLoading: boolean; error: unknown; onRetry: () => void };
function Documents({ flow, isLoading, canManage, canView, approving, onApprove, onDownload, onUpload }: { flow: EmployeeOnboardingFlowDto | null; isLoading: boolean; canManage: boolean; canView: boolean; approving: boolean; onApprove: (id: string) => void; onDownload: (document: EmployeeOnboardingDocumentDto) => Promise<void>; onUpload: () => void }) { if (!canView) return <InlineFeedback tone="info" title="Sin permiso de documentos">No cuentas con acceso a los documentos de incorporación de este empleado.</InlineFeedback>; if (isLoading) return <AsyncState state="loading" title="Cargando documentos" description="Consultamos el expediente de incorporación." />; if (!flow) return <EmptyState title="No hay documentos de incorporación" description="Este empleado todavía no tiene un flujo de incorporación asociado." />; return <div className="space-y-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-lg font-semibold">Documentos de incorporación</h2><p className="mt-1 text-sm text-text-secondary">{flow.documents.length} documento{flow.documents.length === 1 ? "" : "s"} asociado{flow.documents.length === 1 ? "" : "s"} al flujo actual.</p></div>{canManage ? <Button onClick={onUpload}><Upload className="size-4" />Cargar documento</Button> : null}</div>{flow.documents.length ? <div className="grid gap-3">{flow.documents.map((document) => <Card key={document.id} level={2}><CardContent className="flex flex-col gap-4 p-4 sm:flex-row sm:items-center sm:justify-between"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><FileText className="size-4 text-primary" /><p className="truncate font-medium">{document.originalName}</p><DocumentStatus status={document.status} /></div><p className="mt-2 text-sm text-text-secondary">{document.category} · {formatFileSize(document.sizeBytes)} · v{document.version ?? 1}</p>{document.expiresAt ? <p className="mt-1 text-xs text-text-secondary">Vence: {formatDate(document.expiresAt)}</p> : null}{document.rejectionReason ? <p className="mt-1 text-xs text-destructive">Motivo de rechazo: {document.rejectionReason}</p> : null}</div><div className="flex flex-wrap gap-2"><Button variant="secondary" size="sm" onClick={() => void onDownload(document)}><Download className="size-4" />Descargar</Button>{canManage && document.status === "PENDING_REVIEW" ? <Button size="sm" disabled={approving} onClick={() => onApprove(document.id)}><CheckCircle2 className="size-4" />Aprobar</Button> : null}</div></CardContent></Card>)}</div> : <EmptyState title="Aún no hay documentos" description="Carga el primer documento para incorporarlo al expediente del empleado." />}</div>; }
function Compliance({ flow, isLoading, canView }: { flow: EmployeeOnboardingFlowDto | null; isLoading: boolean; canView: boolean }) { if (!canView) return <InlineFeedback tone="info" title="Sin permiso de cumplimiento">No cuentas con acceso al avance de incorporación de este empleado.</InlineFeedback>; if (isLoading) return <AsyncState state="loading" title="Cargando cumplimiento" description="Calculamos el avance desde las tareas de incorporación." />; if (!flow) return <EmptyState title="Sin datos de cumplimiento" description="El cumplimiento se habilita cuando exista un flujo de incorporación para el empleado." />; const required = flow.tasks.filter((task) => task.required !== false); const completed = required.filter((task) => task.status === "COMPLETED").length; const attention = required.filter((task) => task.overdue || task.blocked).length + flow.alerts.length; const score = required.length ? Math.round((completed / required.length) * 100) : flow.progressPercent; return <div className="space-y-5"><div className="grid gap-4 sm:grid-cols-3"><MetricCard label="Cumplimiento" value={`${score}%`} icon={<ShieldCheck className="size-5" />} /><MetricCard label="Requisitos completados" value={`${completed}/${required.length}`} icon={<FileCheck2 className="size-5" />} /><MetricCard label="Requieren atención" value={String(attention)} icon={<AlertTriangle className="size-5" />} /></div><Card level={2}><CardContent className="p-5"><SectionTitle icon={<ShieldCheck className="size-4" />} title="Requisitos de incorporación" /><div className="mt-4 divide-y divide-border-default">{required.length ? required.map((task) => <div key={task.id} className="flex flex-col gap-2 py-4 first:pt-0 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-medium">{task.title}</p><p className="mt-1 text-sm text-text-secondary">{task.dueDate ? `Fecha límite: ${formatDate(task.dueDate)}` : "Sin fecha límite"}{task.blockingReason ? ` · ${task.blockingReason}` : ""}</p></div><TaskStatus task={task} /></div>) : <p className="text-sm text-text-secondary">No hay requisitos configurados en este flujo.</p>}</div></CardContent></Card>{flow.alerts.length ? <InlineFeedback tone="warning" title="Alertas de incorporación">{flow.alerts.map((alert) => alert.message).join(" · ")}</InlineFeedback> : null}</div>; }
function History({ events }: { events: Awaited<ReturnType<typeof fetchEmployeeDetail>>["history"] }) { return <Card level={2}><CardContent className="p-5"><SectionTitle icon={<Clock3 className="size-4" />} title="Actividad del expediente" /><ol className="mt-5 space-y-5 border-l border-border-default pl-5">{events.length ? events.map((event) => <li key={event.id} className="relative"><span className="absolute -left-[1.7rem] top-1 size-3 rounded-full border-2 border-card bg-primary" /><p className="font-medium">{event.title}</p><p className="mt-1 text-sm text-text-secondary">{event.detail}</p><time className="mt-2 block text-xs text-text-secondary">{formatDate(event.at)}</time></li>) : <li className="text-sm text-text-secondary">Todavía no hay eventos de historial.</li>}</ol></CardContent></Card>; }
function EmptyState({ title, description }: { title: string; description: string }) { return <Card level={2}><CardContent className="p-8 text-center"><FileText className="mx-auto size-8 text-text-secondary" /><h2 className="mt-3 font-semibold">{title}</h2><p className="mx-auto mt-2 max-w-md text-sm text-text-secondary">{description}</p></CardContent></Card>; }
function DocumentStatus({ status }: { status: EmployeeOnboardingDocumentDto["status"] }) { const labels = { PENDING_REVIEW: "Pendiente", APPROVED: "Aprobado", REJECTED: "Rechazado", SUPERSEDED: "Reemplazado", DELETED: "Eliminado" }; return <Badge variant={status === "APPROVED" ? "success" : status === "REJECTED" ? "destructive" : "secondary"}>{labels[status]}</Badge>; }
function ComplianceBadge({ status }: { status: string }) { const normalized = status.replaceAll("_", " ").toLowerCase(); const label = normalized.charAt(0).toUpperCase() + normalized.slice(1); const variant = /complete|verified|authorized|registered/.test(normalized) ? "success" : /expired|rejected|failed/.test(normalized) ? "destructive" : "secondary"; return <Badge variant={variant}>{label}</Badge>; }
function TaskStatus({ task }: { task: EmployeeOnboardingFlowDto["tasks"][number] }) { if (task.overdue || task.blocked) return <Badge variant="destructive">Requiere atención</Badge>; if (task.status === "COMPLETED") return <Badge variant="success">Completado</Badge>; return <Badge variant="secondary">Pendiente</Badge>; }
function SectionTitle({ icon, title }: { icon: React.ReactNode; title: string }) { return <h2 className="flex items-center gap-2 font-semibold">{icon}{title}</h2>; }
function Datum({ label, value }: { label: string; value: string }) { return <div><dt className="text-xs font-medium uppercase tracking-wide text-text-secondary">{label}</dt><dd className="mt-1 break-words font-medium">{value}</dd></div>; }
function Metric({ label, value }: { label: string; value: string }) { return <div className="rounded-xl border border-border-default bg-surface-section p-3"><p className="text-xs text-text-secondary">{label}</p><p className="mt-1 text-xl font-semibold">{value}</p></div>; }
function MetricCard({ label, value, icon }: { label: string; value: string; icon: React.ReactNode }) { return <Card level={2}><CardContent className="p-5"><div className="flex items-center justify-between text-text-secondary"><p className="text-sm">{label}</p>{icon}</div><p className="mt-3 text-3xl font-semibold">{value}</p></CardContent></Card>; }
async function downloadDocument(document: EmployeeOnboardingDocumentDto) { const blob = await downloadOnboardingDocument(document.id); const url = URL.createObjectURL(blob); const anchor = window.document.createElement("a"); anchor.href = url; anchor.download = document.originalName; anchor.click(); URL.revokeObjectURL(url); }
function initials(name: string) { return name.split(/\s+/).filter(Boolean).slice(0, 2).map((part) => part[0]).join("").toUpperCase(); }
function statusLabel(status: string) { return ({ ACTIVE: "Activo", INACTIVE: "Inactivo", TERMINATED: "Finalizado" } as Record<string, string>)[status] ?? status; }
function formatDate(value: string) { const date = new Date(value); return Number.isNaN(date.getTime()) ? value : new Intl.DateTimeFormat("es", { dateStyle: "medium" }).format(date); }
function formatFileSize(bytes: number) { if (bytes < 1024) return `${bytes} B`; if (bytes < 1024 * 1024) return `${Math.round(bytes / 1024)} KB`; return `${(bytes / (1024 * 1024)).toFixed(1)} MB`; }
function booleanLabel(value: boolean | null) { return value === null ? "Sin configurar" : value ? "Sí" : "No"; }
