"use client";

import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { DoorOpen, Plus, ShieldCheck, Users } from "lucide-react";
import { toast } from "sonner";
import { createInterviewPool, createInterviewResource, fetchInterviewCoordinationQueue, fetchInterviewerProfiles, fetchInterviewPools, fetchInterviewResources, updateInterviewerProfile } from "@/lib/backend";
import { useAppStore } from "@/store/app-store";
import { InlineFeedback } from "@/components/design-system";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";

export function InterviewCoordinationConsole() {
  const queryClient = useQueryClient();
  const { currentBranch, tenantUsers, can } = useAppStore();
  const [poolOpen, setPoolOpen] = useState(false);
  const [resourceOpen, setResourceOpen] = useState(false);
  const [poolName, setPoolName] = useState("");
  const [poolMembers, setPoolMembers] = useState<string[]>([]);
  const [resource, setResource] = useState({ name: "", type: "ROOM", capacity: 4, location: "" });
  const pools = useQuery({ queryKey: ["interview-pools"], queryFn: fetchInterviewPools });
  const resources = useQuery({ queryKey: ["interview-resources", currentBranch?.id], queryFn: () => fetchInterviewResources(currentBranch?.id), enabled: Boolean(currentBranch?.id) });
  const profiles = useQuery({ queryKey: ["interviewer-profiles"], queryFn: fetchInterviewerProfiles });
  const queue = useQuery({ queryKey: ["interview-coordination-queue"], queryFn: () => fetchInterviewCoordinationQueue() });
  const createPool = useMutation({ mutationFn: () => createInterviewPool({ name: poolName, branchId: currentBranch?.id, members: poolMembers.map((userId, index) => ({ userId, defaultRole: index === 0 ? "LEAD" : "PANELIST", priority: index + 1 })) }), onSuccess: async () => { toast.success("Pool creado"); setPoolOpen(false); setPoolName(""); setPoolMembers([]); await queryClient.invalidateQueries({ queryKey: ["interview-pools"] }); } });
  const createResource = useMutation({ mutationFn: () => createInterviewResource({ branchId: currentBranch!.id, ...resource }), onSuccess: async () => { toast.success("Recurso creado"); setResourceOpen(false); setResource({ name: "", type: "ROOM", capacity: 4, location: "" }); await queryClient.invalidateQueries({ queryKey: ["interview-resources"] }); } });
  const profile = useMutation({ mutationFn: ({ userId, trainingStatus, daily, weekly }: { userId: string; trainingStatus: string; daily: number; weekly: number }) => updateInterviewerProfile(userId, { trainingStatus, maxInterviewsPerDay: daily, maxInterviewsPerWeek: weekly, shadowSessionsRequired: 2, autoSubstitutionEnabled: true }), onSuccess: async () => { toast.success("Perfil de entrevistador actualizado"); await queryClient.invalidateQueries({ queryKey: ["interviewer-profiles"] }); } });

  return <Card level={1}><CardHeader><div className="flex flex-wrap items-center justify-between gap-3"><div><CardTitle>Centro de coordinación</CardTitle><p className="mt-1 text-sm text-text-secondary">Pools, carga, preparación de entrevistadores, salas y pendientes operativos.</p></div>{can("interviews.schedule") ? <div className="flex gap-2"><Button size="sm" variant="secondary" onClick={() => setPoolOpen(true)}><Users className="size-4" />Nuevo pool</Button><Button size="sm" variant="secondary" onClick={() => setResourceOpen(true)} disabled={!currentBranch}><DoorOpen className="size-4" />Sala o recurso</Button></div> : null}</div></CardHeader><CardContent className="space-y-5"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Metric label="Pools activos" value={pools.data?.length ?? 0} /><Metric label="Salas y recursos" value={resources.data?.length ?? 0} /><Metric label="Invitaciones pendientes" value={queue.data?.meta.interviewCount ?? 0} /><Metric label="Enlaces por reservar" value={queue.data?.meta.requestCount ?? 0} /></div>{queue.data && (queue.data.interviews.length || queue.data.schedulingRequests.length) ? <div className="grid gap-3 lg:grid-cols-2"><section><h3 className="font-semibold">Atención del coordinador</h3><div className="mt-2 space-y-2">{queue.data.interviews.slice(0, 5).map((item) => <div key={item.id} className="rounded-xl border p-3 text-sm"><div className="flex justify-between gap-2"><strong>{item.title}</strong><Badge variant={item.calendarSyncStatus === "FAILED" ? "destructive" : "secondary"}>{item.calendarSyncStatus === "FAILED" ? "Error calendario" : "Confirmaciones pendientes"}</Badge></div><p className="text-text-secondary">{item.application?.candidate.fullName} · {new Date(item.startsAt).toLocaleString()}</p></div>)}</div></section><section><h3 className="font-semibold">Autoservicio pendiente</h3><div className="mt-2 space-y-2">{queue.data.schedulingRequests.slice(0, 5).map((item) => <div key={item.id} className="rounded-xl border p-3 text-sm"><strong>{item.title}</strong><p className="text-text-secondary">{item.application.candidate.fullName} · vence {new Date(item.expiresAt).toLocaleDateString()}</p></div>)}</div></section></div> : <InlineFeedback tone="success" title="Cola bajo control">No hay sincronizaciones fallidas ni confirmaciones pendientes.</InlineFeedback>}
    <section><h3 className="font-semibold">Preparación y límites</h3><div className="mt-3 grid gap-2 lg:grid-cols-2">{profiles.data?.map((item) => { const current = item.interviewerProfile; return <div key={item.id} className="grid items-center gap-2 rounded-xl border p-3 sm:grid-cols-[1fr_150px_70px_70px_auto]"><div><p className="font-medium">{item.firstName} {item.lastName}</p><p className="text-xs text-text-secondary">{current?.shadowSessionsCompleted ?? 0}/{current?.shadowSessionsRequired ?? 2} shadows</p></div><Select defaultValue={current?.trainingStatus ?? "NOT_STARTED"} onValueChange={(trainingStatus) => profile.mutate({ userId: item.id, trainingStatus, daily: current?.maxInterviewsPerDay ?? 4, weekly: current?.maxInterviewsPerWeek ?? 12 })}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="NOT_STARTED">Sin iniciar</SelectItem><SelectItem value="IN_TRAINING">En formación</SelectItem><SelectItem value="SHADOWING">Shadowing</SelectItem><SelectItem value="CERTIFIED">Certificado</SelectItem><SelectItem value="SUSPENDED">Suspendido</SelectItem></SelectContent></Select><span className="text-center text-xs">{current?.maxInterviewsPerDay ?? 4}/día</span><span className="text-center text-xs">{current?.maxInterviewsPerWeek ?? 12}/sem</span><ShieldCheck className={`size-5 ${current?.trainingStatus === "CERTIFIED" ? "text-status-success" : "text-text-secondary"}`} /></div>; })}</div></section></CardContent>
    <Dialog open={poolOpen} onOpenChange={setPoolOpen}><DialogContent><DialogHeader><DialogTitle>Crear pool de entrevistadores</DialogTitle><DialogDescription>El orden define prioridad para sustituciones automáticas.</DialogDescription></DialogHeader><div className="space-y-4"><Input value={poolName} onChange={(event) => setPoolName(event.target.value)} placeholder="Nombre del pool" /><div className="max-h-64 space-y-2 overflow-y-auto rounded-xl border p-3">{tenantUsers.map((user) => <label key={user.id} className="flex items-center gap-2 text-sm"><input type="checkbox" checked={poolMembers.includes(user.id)} onChange={(event) => setPoolMembers((current) => event.target.checked ? [...current, user.id] : current.filter((id) => id !== user.id))} />{user.fullName} · {user.role}</label>)}</div><Button className="w-full" disabled={!poolName.trim() || !poolMembers.length || createPool.isPending} onClick={() => createPool.mutate()}><Plus className="size-4" />Crear pool</Button></div></DialogContent></Dialog>
    <Dialog open={resourceOpen} onOpenChange={setResourceOpen}><DialogContent><DialogHeader><DialogTitle>Crear sala o recurso</DialogTitle><DialogDescription>Las reservas se validarán contra cruces de horario.</DialogDescription></DialogHeader><div className="space-y-4"><Input value={resource.name} onChange={(event) => setResource({ ...resource, name: event.target.value })} placeholder="Nombre" /><Select value={resource.type} onValueChange={(type) => setResource({ ...resource, type })}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="ROOM">Sala física</SelectItem><SelectItem value="VIDEO_ROOM">Sala de video</SelectItem><SelectItem value="EQUIPMENT">Equipo</SelectItem><SelectItem value="ACCESSIBILITY">Apoyo de accesibilidad</SelectItem></SelectContent></Select><Input type="number" min={1} value={resource.capacity} onChange={(event) => setResource({ ...resource, capacity: Number(event.target.value) })} placeholder="Capacidad" /><Input value={resource.location} onChange={(event) => setResource({ ...resource, location: event.target.value })} placeholder="Ubicación" /><Button className="w-full" disabled={!resource.name.trim() || !currentBranch || createResource.isPending} onClick={() => createResource.mutate()}>Crear recurso</Button></div></DialogContent></Dialog>
  </Card>;
}

function Metric({ label, value }: { label: string; value: number }) { return <div className="rounded-xl bg-surface-section p-4"><p className="text-sm text-text-secondary">{label}</p><p className="mt-1 text-2xl font-semibold">{value}</p></div>; }
