"use client";
import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Check, PackageCheck, Plus, Truck } from "lucide-react";
import { approveInventoryPurchaseOrder, createInventoryPurchaseOrder, createInventorySupplier, fetchInventoryCatalog, fetchInventoryPurchaseOrders, fetchInventorySuppliers, receiveInventoryPurchaseOrder } from "@/lib/backend";
import { useAppStore } from "@/store/app-store";
import { AsyncState } from "@/components/async-state";
import { PageHeader } from "@/components/design-system";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
export function InventoryPurchasesPanel() { const { currentBranch } = useAppStore(); const qc = useQueryClient(); const [open, setOpen] = useState<"supplier"|"order"|null>(null); const suppliers = useQuery({queryKey:["inventory-suppliers"],queryFn:fetchInventorySuppliers}); const catalog=useQuery({queryKey:["inventory-catalog"],queryFn:fetchInventoryCatalog}); const orders=useQuery({queryKey:["inventory-orders",currentBranch?.id],queryFn:()=>fetchInventoryPurchaseOrders(currentBranch?.id)}); const refresh=()=>Promise.all([qc.invalidateQueries({queryKey:["inventory-orders"]}),qc.invalidateQueries({queryKey:["inventory-warehouse"]})]); return <div className="space-y-6"><PageHeader eyebrow="Abastecimiento" title="Compras y proveedores" description="Solicita, aprueba y recibe compras con impacto trazable sobre el stock." actions={<div className="flex gap-2"><Button variant="secondary" onClick={()=>setOpen("supplier")}><Plus className="size-4"/>Proveedor</Button><Button onClick={()=>setOpen("order")}><Plus className="size-4"/>Orden de compra</Button></div>}/>{orders.isLoading?<AsyncState state="loading" title="Cargando órdenes"/>:null}<div className="grid gap-3 lg:grid-cols-2">{orders.data?.map(order=><Card key={order.id} level={2}><CardContent className="space-y-3 p-5"><div className="flex justify-between gap-3"><div><p className="font-semibold">{order.code}</p><p className="text-sm text-text-secondary">{order.lines.length} líneas · {order.currency} {order.totalAmount}</p></div><Badge>{order.status}</Badge></div><div className="flex flex-wrap gap-2">{order.status==="DRAFT"?<Button size="sm" onClick={()=>approveInventoryPurchaseOrder(order.id).then(refresh)}><Check className="size-4"/>Aprobar</Button>:null}{["APPROVED","PARTIALLY_RECEIVED"].includes(order.status)?<Button size="sm" variant="secondary" onClick={()=>receiveInventoryPurchaseOrder(order.id,order.lines.filter(line=>line.receivedQty<line.quantity).map(line=>({lineId:line.id,quantity:line.quantity-line.receivedQty}))).then(refresh)}><Truck className="size-4"/>Recibir pendiente</Button>:null}</div></CardContent></Card>)}</div><PurchaseDialog kind={open} suppliers={suppliers.data??[]} catalog={catalog.data??[]} branchId={currentBranch?.id??""} onClose={()=>setOpen(null)} onSuccess={async()=>{await refresh();setOpen(null);}}/></div>; }
function PurchaseDialog({kind,suppliers,catalog,branchId,onClose,onSuccess}:{kind:"supplier"|"order"|null;suppliers:Array<{id:string;name:string}>;catalog:Array<{id:string;name:string;sku:string}>;branchId:string;onClose:()=>void;onSuccess:()=>Promise<void>}){const [v,setV]=useState<Record<string,string>>({});const m=useMutation({mutationFn:()=>kind==="supplier"?createInventorySupplier({name:v.name,email:v.email,phone:v.phone,taxId:v.taxId}):createInventoryPurchaseOrder({branchId,supplierId:v.supplierId,code:v.code,currency:v.currency||"USD",budgetAmount:v.budget?Number(v.budget):undefined,notes:v.notes,lines:[{itemId:v.itemId,quantity:Number(v.quantity),unitCost:Number(v.unitCost)}]}),onSuccess});const f=(label:string,key:string,select?:Array<{id:string;name:string}>)=><div><Label>{label}</Label>{select?<Select value={v[key]} onValueChange={x=>setV({...v,[key]:x})}><SelectTrigger><SelectValue placeholder="Seleccionar"/></SelectTrigger><SelectContent>{select.map(x=><SelectItem key={x.id} value={x.id}>{x.name}</SelectItem>)}</SelectContent></Select>:<Input value={v[key]??""} onChange={e=>setV({...v,[key]:e.target.value})}/>}</div>;return <Dialog open={!!kind} onOpenChange={x=>!x&&onClose()}><DialogContent><DialogHeader><DialogTitle>{kind==="supplier"?"Nuevo proveedor":"Nueva orden de compra"}</DialogTitle></DialogHeader><div className="space-y-3">{kind==="supplier"?<>{f("Nombre","name")}{f("Correo","email")}{f("Teléfono","phone")}{f("Identificación fiscal","taxId")}</>:<>{f("Código","code")}{f("Proveedor","supplierId",suppliers)}{f("Artículo","itemId",catalog.map(x=>({id:x.id,name:`${x.name} · ${x.sku}`})))}{f("Cantidad","quantity")}{f("Costo unitario","unitCost")}{f("Moneda","currency")}{f("Presupuesto","budget")}{f("Notas","notes")}</>}<Button className="w-full" disabled={m.isPending} onClick={()=>m.mutate()}>{m.isPending?"Guardando…":"Guardar"}</Button></div></DialogContent></Dialog>}
