"use client";

import { useState, type ReactNode } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Pencil, Plus, RefreshCw, X } from "lucide-react";
import {
  createRestaurantCategory, createRestaurantIngredient, createRestaurantSupplier, createRestaurantUnit, createRestaurantWarehouse,
  deactivateRestaurantCategory, deactivateRestaurantIngredient, deactivateRestaurantSupplier, deactivateRestaurantUnit, deactivateRestaurantWarehouse,
  fetchRestaurantCategories, fetchRestaurantIngredients, fetchRestaurantSuppliers, fetchRestaurantUnits, fetchRestaurantWarehouses,
  updateRestaurantCategory, updateRestaurantIngredient, updateRestaurantSupplier, updateRestaurantUnit, updateRestaurantWarehouse,
  getApiErrorMessage,
} from "@/lib/backend";
import { validateRestaurantCatalogForm, type RestaurantCatalogKind } from "@/lib/restaurant-inventory";
import { useAppStore } from "@/store/app-store";
import { AsyncState } from "@/components/async-state";
import { InlineFeedback, PageHeader } from "@/components/design-system";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";

type RecordValue = Record<string, unknown> & { id: string; name?: string; status?: string };
type FormValues = Record<string, string>;
const labels: Record<RestaurantCatalogKind, string> = { categories: "Categorías", units: "Unidades de medida", suppliers: "Proveedores", warehouses: "Almacenes", ingredients: "Ingredientes" };

const fetchers = { categories: fetchRestaurantCategories, units: fetchRestaurantUnits, suppliers: fetchRestaurantSuppliers, warehouses: fetchRestaurantWarehouses, ingredients: fetchRestaurantIngredients };
const creators = { categories: createRestaurantCategory, units: createRestaurantUnit, suppliers: createRestaurantSupplier, warehouses: createRestaurantWarehouse, ingredients: createRestaurantIngredient };
const updaters = { categories: updateRestaurantCategory, units: updateRestaurantUnit, suppliers: updateRestaurantSupplier, warehouses: updateRestaurantWarehouse, ingredients: updateRestaurantIngredient };
const deactivators = { categories: deactivateRestaurantCategory, units: deactivateRestaurantUnit, suppliers: deactivateRestaurantSupplier, warehouses: deactivateRestaurantWarehouse, ingredients: deactivateRestaurantIngredient };

export function RestaurantInventoryCatalog({ kind }: { kind: RestaurantCatalogKind }) {
  const { can, currentBranch } = useAppStore();
  const canManage = can("restaurant_inventory.manage");
  const queryClient = useQueryClient();
  const [search, setSearch] = useState("");
  const [status, setStatus] = useState("ACTIVE");
  const [page, setPage] = useState(1);
  const [sortBy, setSortBy] = useState("name");
  const [sortOrder, setSortOrder] = useState<"asc" | "desc">("asc");
  const [editing, setEditing] = useState<RecordValue | null>(null);
  const [creating, setCreating] = useState(false);
  const query = useQuery<{ data: RecordValue[]; page: number; pageSize: number; total: number; totalPages: number }>({ queryKey: ["restaurant-catalog", kind, search, status, page, sortBy, sortOrder], queryFn: () => fetchers[kind]({ search, status, page, pageSize: 10, sortBy, sortOrder }) as unknown as Promise<{ data: RecordValue[]; page: number; pageSize: number; total: number; totalPages: number }> });
  const mutation = useMutation<unknown, Error, { mode: "save" | "deactivate"; id?: string; values: FormValues }>({ mutationFn: (input) => {
    if (input.mode === "deactivate") return deactivators[kind](input.id!);
    const values = normalizeValues(kind, input.values, currentBranch?.id);
    return input.id ? updaters[kind](input.id, values) : creators[kind](values);
  }, onSuccess: async () => { setCreating(false); setEditing(null); await queryClient.invalidateQueries({ queryKey: ["restaurant-catalog", kind] }); } });
  const data = (query.data?.data ?? []) as RecordValue[];
  const openForm = (item?: RecordValue) => item ? setEditing(item) : setCreating(true);
  return <div className="space-y-4">
    <PageHeader eyebrow="Catálogo" title={labels[kind]} description="Datos maestros administrados por empresa y consultados desde el backend." actions={canManage ? <Button onClick={() => openForm()}><Plus className="size-4" />Nuevo</Button> : undefined} />
    <Card level={2}><CardContent className="flex flex-wrap items-end gap-3 p-4"><div className="min-w-[240px] flex-1"><Label htmlFor={`catalog-search-${kind}`}>Buscar</Label><Input id={`catalog-search-${kind}`} value={search} onChange={(event) => { setSearch(event.target.value); setPage(1); }} placeholder="Nombre, código o descripción" /></div><div><Label htmlFor={`catalog-status-${kind}`}>Estado</Label><select id={`catalog-status-${kind}`} className="h-11 rounded-2xl border border-border-default bg-surface-elevated px-3" value={status} onChange={(event) => { setStatus(event.target.value); setPage(1); }}><option value="ACTIVE">Activos</option><option value="INACTIVE">Inactivos</option></select></div><Button variant="secondary" onClick={() => void query.refetch()}><RefreshCw className="size-4" />Actualizar</Button></CardContent></Card>
    {mutation.error ? <InlineFeedback tone="danger" title="No se pudo completar la operación">{getApiErrorMessage(mutation.error, "Revisa los datos e inténtalo de nuevo.")}</InlineFeedback> : null}
    {query.isLoading ? <AsyncState state="loading" /> : query.error ? <AsyncState state="error" onRetry={() => void query.refetch()} description={getApiErrorMessage(query.error, "No fue posible cargar el catálogo.")} /> : <CatalogTable kind={kind} data={data} canManage={canManage} sortBy={sortBy} sortOrder={sortOrder} onSort={(next) => { setSortOrder(sortBy === next && sortOrder === "asc" ? "desc" : "asc"); setSortBy(next); }} onEdit={openForm} onDeactivate={(item) => { if (window.confirm(`¿Desactivar ${item.name ?? "este registro"}?`)) mutation.mutate({ mode: "deactivate", id: item.id, values: {} }); }} />}
    {!query.isLoading && !query.error ? <div className="flex items-center justify-between text-sm text-text-secondary"><span>{query.data?.total ?? 0} registros</span><span className="flex items-center gap-2"><Button size="sm" variant="secondary" disabled={page <= 1} onClick={() => setPage((value) => value - 1)}>Anterior</Button><span>Página {query.data?.page ?? page} de {query.data?.totalPages ?? 1}</span><Button size="sm" variant="secondary" disabled={page >= (query.data?.totalPages ?? 1)} onClick={() => setPage((value) => value + 1)}>Siguiente</Button></span></div> : null}
    {(creating || editing) ? <CatalogForm kind={kind} item={editing} pending={mutation.isPending} error={mutation.error} branchId={currentBranch?.id} onClose={() => { setCreating(false); setEditing(null); }} onSubmit={(values) => mutation.mutate({ mode: "save", id: editing?.id, values })} /> : null}
  </div>;
}

function CatalogTable({ kind, data, canManage, sortBy, sortOrder, onSort, onEdit, onDeactivate }: { kind: RestaurantCatalogKind; data: RecordValue[]; canManage: boolean; sortBy: string; sortOrder: "asc" | "desc"; onSort: (key: string) => void; onEdit: (item: RecordValue) => void; onDeactivate: (item: RecordValue) => void }) {
  const headers = kind === "categories" ? [["name", "Nombre"], ["description", "Descripción"]] : kind === "units" ? [["name", "Nombre"], ["abbreviation", "Abreviatura"], ["type", "Tipo"], ["conversionFactor", "Conversión"]] : kind === "suppliers" ? [["name", "Nombre"], ["contactName", "Contacto"], ["email", "Correo"], ["phone", "Teléfono"]] : kind === "warehouses" ? [["code", "Código"], ["name", "Nombre"], ["location", "Ubicación"], ["branchName", "Sucursal"]] : [["sku", "SKU"], ["name", "Nombre"], ["category", "Categoría"], ["inventoryUnit", "Unidad"], ["minimumStock", "Stock mínimo"], ["averageCost", "Costo promedio"]];
  const displayValue = (item: RecordValue, key: string) => key === "location" ? String(item.location ?? item.address ?? ([item.city, item.state].filter(Boolean).join(", ") || "Ubicación no registrada")) : key === "branchName" ? String(item.branchName ?? item.branchId ?? "-") : String(item[key] ?? "-");
  return <div className="overflow-x-auto rounded-2xl border border-border-default">{data.length === 0 ? <div className="p-10 text-center text-sm text-text-secondary">No hay registros para los filtros actuales.</div> : <table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-surface-interactive text-text-secondary"><tr>{headers.map(([key, label]) => <th key={key} className="px-4 py-3"><button className="font-medium" onClick={() => onSort(key)}>{label}{sortBy === key ? ` ${sortOrder === "asc" ? "↑" : "↓"}` : ""}</button></th>)}<th className="px-4 py-3">Estado</th>{canManage ? <th className="px-4 py-3">Acciones</th> : null}</tr></thead><tbody className="divide-y divide-border-default">{data.map((item) => <tr key={item.id}>{headers.map(([key]) => <td key={key} className="px-4 py-3">{displayValue(item, key)}</td>)}<td className="px-4 py-3"><Badge variant={item.status === "ACTIVE" ? "default" : "secondary"}>{item.status ?? "-"}</Badge></td>{canManage ? <td className="px-4 py-3"><span className="flex gap-2"><Button size="sm" variant="secondary" onClick={() => onEdit(item)}><Pencil className="size-4" />Editar rápido</Button>{item.status === "ACTIVE" ? <Button size="sm" variant="ghost" onClick={() => onDeactivate(item)}>Desactivar</Button> : null}</span></td> : null}</tr>)}</tbody></table>}</div>;
}

function CatalogForm({ kind, item, pending, error, branchId, onClose, onSubmit }: { kind: RestaurantCatalogKind; item: RecordValue | null; pending: boolean; error: unknown; branchId?: string; onClose: () => void; onSubmit: (values: FormValues) => void }) {
  const categoryQuery = useQuery({ queryKey: ["restaurant-catalog", "categories", "ACTIVE"], queryFn: () => fetchRestaurantCategories({ status: "ACTIVE", pageSize: 200 }), enabled: kind === "ingredients" });
  const unitQuery = useQuery({ queryKey: ["restaurant-catalog", "units", "ACTIVE"], queryFn: () => fetchRestaurantUnits({ status: "ACTIVE", pageSize: 200 }), enabled: kind === "ingredients" });
  const [values, setValues] = useState<FormValues>(() => initialValues(kind, item, branchId));
  const [errors, setErrors] = useState<Record<string, string>>({});
  if (!item && !branchId && kind === "warehouses") return <CatalogModal title="Nuevo almacén" onClose={onClose}><InlineFeedback tone="warning" title="Sucursal requerida">Selecciona una sucursal antes de crear un almacén.</InlineFeedback></CatalogModal>;
  const update = (key: string, value: string) => setValues((current) => ({ ...current, [key]: value }));
  const fields = fieldsFor(kind);
  return <CatalogModal title={`${item ? "Editar" : "Nuevo"} ${labels[kind].toLowerCase()}`} onClose={onClose}><div className="grid gap-3 sm:grid-cols-2">{fields.map((field) => <div key={field.key}><Label htmlFor={`catalog-${field.key}`}>{field.label}</Label>{field.select ? <select id={`catalog-${field.key}`} className="h-11 w-full rounded-2xl border border-border-default bg-surface-elevated px-3" value={values[field.key] ?? ""} onChange={(event) => update(field.key, event.target.value)}><option value="">Seleccionar</option>{field.select.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select> : <Input id={`catalog-${field.key}`} type={field.type ?? "text"} value={values[field.key] ?? ""} onChange={(event) => update(field.key, event.target.value)} />}{errors[field.key] ? <p className="mt-1 text-xs text-danger">{errors[field.key]}</p> : null}</div>)}{kind === "ingredients" ? <><SelectField id="catalog-categoryId" label="Categoría" value={values.categoryId ?? ""} options={(categoryQuery.data?.data ?? []).map((record) => [String(record.id), String(record.name)] as [string, string])} onChange={(value) => update("categoryId", value)} /><SelectField id="catalog-inventoryUnitId" label="Unidad de inventario" value={values.inventoryUnitId ?? ""} options={(unitQuery.data?.data ?? []).map((record) => [String(record.id), String(record.name)] as [string, string])} onChange={(value) => update("inventoryUnitId", value)} /><SelectField id="catalog-purchaseUnitId" label="Unidad de compra" value={values.purchaseUnitId ?? ""} options={(unitQuery.data?.data ?? []).map((record) => [String(record.id), String(record.name)] as [string, string])} onChange={(value) => update("purchaseUnitId", value)} /></> : null}</div>{categoryQuery.error || unitQuery.error ? <InlineFeedback tone="danger" title="No se pudieron cargar las opciones">{getApiErrorMessage(categoryQuery.error ?? unitQuery.error, "Reintenta para cargar categorías y unidades.")}</InlineFeedback> : null}{error ? <InlineFeedback tone="danger" title="No se pudo guardar">{getApiErrorMessage(error, "Revisa los datos.")}</InlineFeedback> : null}<div className="flex justify-end gap-2"><Button variant="secondary" onClick={onClose}>Cancelar</Button><Button disabled={pending} onClick={() => { const nextErrors = validateRestaurantCatalogForm(kind, values); setErrors(nextErrors); if (!Object.keys(nextErrors).length) onSubmit(values); }}>{pending ? "Guardando…" : "Guardar"}</Button></div></CatalogModal>;
}

function SelectField({ id, label, value, options, onChange }: { id: string; label: string; value: string; options: [string, string][]; onChange: (value: string) => void }) { return <div><Label htmlFor={id}>{label}</Label><select id={id} className="h-11 w-full rounded-2xl border border-border-default bg-surface-elevated px-3" value={value} onChange={(event) => onChange(event.target.value)}><option value="">Seleccionar</option>{options.map(([optionValue, optionLabel]) => <option key={optionValue} value={optionValue}>{optionLabel}</option>)}</select></div>; }
function CatalogModal({ title, onClose, children }: { title: string; onClose: () => void; children: ReactNode }) { return <div className="fixed inset-0 z-50 grid place-items-center overflow-y-auto bg-black/40 p-4"><Card className="w-full max-w-2xl"><CardContent className="space-y-4 p-6"><div className="flex items-center justify-between"><h2 className="text-xl font-semibold">{title}</h2><Button variant="ghost" onClick={onClose} aria-label="Cerrar"><X className="size-4" /></Button></div>{children}</CardContent></Card></div>; }

function fieldsFor(kind: RestaurantCatalogKind) { if (kind === "categories") return [{ key: "name", label: "Nombre" }, { key: "description", label: "Descripción" }]; if (kind === "units") return [{ key: "name", label: "Nombre" }, { key: "abbreviation", label: "Abreviatura" }, { key: "type", label: "Tipo", select: [["WEIGHT", "Peso"], ["VOLUME", "Volumen"], ["UNIT", "Unidad"]] as [string, string][] }, { key: "conversionFactor", label: "Factor de conversión", type: "number" }, { key: "decimalPrecision", label: "Decimales", type: "number" }]; if (kind === "suppliers") return [{ key: "name", label: "Nombre" }, { key: "contactName", label: "Contacto" }, { key: "email", label: "Correo", type: "email" }, { key: "phone", label: "Teléfono" }, { key: "taxId", label: "Identificación fiscal" }]; if (kind === "warehouses") return [{ key: "name", label: "Nombre" }, { key: "code", label: "Código" }, { key: "location", label: "Ubicación" }]; return [{ key: "sku", label: "SKU" }, { key: "name", label: "Nombre" }, { key: "purchaseConversionFactor", label: "Factor de conversión", type: "number" }, { key: "minimumStock", label: "Stock mínimo", type: "number" }]; }
function initialValues(kind: RestaurantCatalogKind, item: RecordValue | null, branchId?: string): FormValues { const base: FormValues = { name: String(item?.name ?? ""), description: String(item?.description ?? ""), abbreviation: String(item?.abbreviation ?? ""), type: String(item?.type ?? "WEIGHT"), conversionFactor: String(item?.conversionFactor ?? "1"), decimalPrecision: String(item?.decimalPrecision ?? "2"), contactName: String(item?.contactName ?? ""), email: String(item?.email ?? ""), phone: String(item?.phone ?? ""), taxId: String(item?.taxId ?? ""), code: String(item?.code ?? ""), location: String(item?.location ?? item?.address ?? ""), branchId: String(item?.branchId ?? branchId ?? ""), sku: String(item?.sku ?? ""), categoryId: String(item?.categoryId ?? ""), inventoryUnitId: String(item?.inventoryUnitId ?? ""), purchaseUnitId: String(item?.purchaseUnitId ?? ""), purchaseConversionFactor: String(item?.purchaseConversionFactor ?? item?.conversionFactor ?? "1"), minimumStock: String(item?.minimumStock ?? "0") }; return kind === "ingredients" ? base : base; }
function normalizeValues(kind: RestaurantCatalogKind, values: FormValues, branchId?: string): Record<string, unknown> { const input: Record<string, unknown> = { ...values }; ["conversionFactor", "decimalPrecision", "purchaseConversionFactor", "minimumStock"].forEach((key) => { if (key in input) input[key] = Number(input[key]); }); if (kind === "warehouses") input.branchId = values.branchId || branchId; delete input.status; return input; }
