"use client";

import { useState } from "react";
import { Check, FileUp, Plus, Send, Truck, X } from "lucide-react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import {
  approveRestaurantPurchaseOrder, convertRestaurantPurchaseSuggestions, createRestaurantPurchaseOrder,
  fetchRestaurantIngredients, fetchRestaurantInvoices, fetchRestaurantPriceHistory,
  fetchRestaurantPurchaseOrders, fetchRestaurantPurchaseSuggestions, fetchRestaurantSuppliers,
  getApiErrorMessage, processRestaurantInvoice, receiveRestaurantPurchaseOrder,
  rejectRestaurantPurchaseOrder, submitRestaurantPurchaseOrder, uploadRestaurantInvoice,
} from "@/lib/backend";
import { useAppStore } from "@/store/app-store";
import { useRestaurantInventoryContext } from "@/components/restaurant-inventory-context";
import { AsyncState } from "@/components/async-state";
import { InlineFeedback, PageHeader } from "@/components/design-system";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";

type PurchaseLine = { ingredientId: string; quantity: string; unitCost: string };
type View = "orders" | "prices" | "suggestions" | "invoices";

export function RestaurantPurchasingWorkspace({ initialView = "orders" }: { initialView?: View }) {
  const [view, setView] = useState<View>(initialView);
  return <div className="space-y-5"><PageHeader eyebrow="Abastecimiento" title="Compras comerciales" description="Ordena, aprueba, recibe y controla costos de proveedores desde un mismo flujo." /><nav className="flex flex-wrap gap-2" aria-label="Compras comerciales"><Button variant={view === "orders" ? "default" : "secondary"} onClick={() => setView("orders")}>Órdenes de compra</Button><Button variant={view === "prices" ? "default" : "secondary"} onClick={() => setView("prices")}>Precios por proveedor</Button><Button variant={view === "suggestions" ? "default" : "secondary"} onClick={() => setView("suggestions")}>Sugerencias y cobertura</Button><Button variant={view === "invoices" ? "default" : "secondary"} onClick={() => setView("invoices")}>Facturas OCR</Button></nav>{view === "orders" ? <PurchaseOrders /> : null}{view === "prices" ? <PriceHistory /> : null}{view === "suggestions" ? <PurchaseSuggestions /> : null}{view === "invoices" ? <InvoiceInbox /> : null}</div>;
}

function PurchaseOrders() {
  const { currentBranch } = useAppStore();
  const { warehouseId, warehouseName } = useRestaurantInventoryContext();
  const qc = useQueryClient();
  const [creating, setCreating] = useState(false);
  const orders = useQuery({ queryKey: ["restaurant-purchase-orders", currentBranch?.id, warehouseId], queryFn: () => fetchRestaurantPurchaseOrders({ branchId: currentBranch?.id, warehouseId }) });
  const action = useMutation({ mutationFn: ({ id, type }: { id: string; type: "submit" | "approve" | "reject" }) => type === "submit" ? submitRestaurantPurchaseOrder(id) : type === "approve" ? approveRestaurantPurchaseOrder(id) : rejectRestaurantPurchaseOrder(id, "Revisión requerida por compras"), onSuccess: () => void qc.invalidateQueries({ queryKey: ["restaurant-purchase-orders"] }) });
  const receive = useMutation({ mutationFn: ({ id, lines }: { id: string; lines: Array<{ lineId: string; quantity: number }> }) => receiveRestaurantPurchaseOrder(id, lines), onSuccess: () => void qc.invalidateQueries({ queryKey: ["restaurant-purchase-orders"] }) });
  return <div className="space-y-4">{action.error || receive.error ? <InlineFeedback tone="danger" title="No se pudo actualizar la orden">{getApiErrorMessage(action.error ?? receive.error, "Revisa el estado y los permisos de la orden.")}</InlineFeedback> : null}{creating ? <PurchaseOrderForm branchId={currentBranch?.id} warehouseId={warehouseId} warehouseName={warehouseName} onClose={() => setCreating(false)} onSaved={() => { setCreating(false); void qc.invalidateQueries({ queryKey: ["restaurant-purchase-orders"] }); }} /> : <><Card level={1}><CardContent className="flex flex-wrap items-center justify-between gap-3 p-5"><div><h2 className="font-semibold">Órdenes de compra</h2><p className="text-sm text-text-secondary">Recepción parcial, diferencias de precio y aprobación quedan trazadas.</p></div><Button onClick={() => setCreating(true)} disabled={!currentBranch?.id || !warehouseId}><Plus className="size-4" />Nueva orden</Button></CardContent></Card><PurchaseOrderTable orders={orders.data ?? []} loading={orders.isLoading} error={orders.error} onRetry={() => void orders.refetch()} onAction={(id, type) => action.mutate({ id, type })} onReceive={(order) => receive.mutate({ id: order.id, lines: order.lines.filter((line) => Number(line.quantity) > Number(line.receivedQuantity ?? 0)).map((line) => ({ lineId: line.id, quantity: Number(line.quantity) - Number(line.receivedQuantity ?? 0) })) })} /></>}</div>;
}

function PurchaseOrderForm({ branchId, warehouseId, warehouseName, onClose, onSaved }: { branchId?: string; warehouseId: string; warehouseName: string; onClose: () => void; onSaved: () => void }) {
  const { currentUser } = useAppStore();
  const suppliers = useQuery({ queryKey: ["restaurant-purchase-suppliers"], queryFn: () => fetchRestaurantSuppliers({ status: "ACTIVE", pageSize: 200 }) });
  const ingredients = useQuery({ queryKey: ["restaurant-purchase-ingredients"], queryFn: () => fetchRestaurantIngredients({ status: "ACTIVE", pageSize: 200 }) });
  const [supplierId, setSupplierId] = useState("");
  const [expectedAt, setExpectedAt] = useState("");
  const [lines, setLines] = useState<PurchaseLine[]>([{ ingredientId: "", quantity: "", unitCost: "" }]);
  const save = useMutation({ mutationFn: () => createRestaurantPurchaseOrder({ branchId, warehouseId, supplierId, expectedAt: expectedAt || undefined, createdBy: currentUser.id, lines: lines.map((line) => ({ ingredientId: line.ingredientId, quantity: Number(line.quantity), unitCost: Number(line.unitCost) })) }), onSuccess: onSaved });
  const invalid = !branchId || !warehouseId || !supplierId || lines.some((line) => !line.ingredientId || Number(line.quantity) <= 0 || Number(line.unitCost) < 0);
  return <Card level={1}><CardContent className="space-y-5 p-5"><div className="flex items-center justify-between gap-3"><div><h2 className="text-xl font-semibold">Nueva orden de compra</h2><p className="text-sm text-text-secondary">Almacén: {warehouseName}</p></div><Button variant="ghost" onClick={onClose} aria-label="Cerrar"><X className="size-4" /></Button></div>{save.error ? <InlineFeedback tone="danger" title="No se pudo guardar">{getApiErrorMessage(save.error, "El backend no pudo crear la orden.")}</InlineFeedback> : null}<div className="grid gap-3 sm:grid-cols-2"><Select id="purchase-supplier" label="Proveedor" value={supplierId} options={(suppliers.data?.data ?? []).map((item) => ({ id: item.id, label: item.name }))} onChange={setSupplierId} /><div><Label htmlFor="purchase-expected">Fecha esperada</Label><Input id="purchase-expected" type="date" value={expectedAt} onChange={(event) => setExpectedAt(event.target.value)} /></div></div><div className="space-y-3"><div className="flex items-center justify-between"><h3 className="font-semibold">Productos</h3><Button size="sm" variant="secondary" onClick={() => setLines([...lines, { ingredientId: "", quantity: "", unitCost: "" }])}><Plus className="size-4" />Agregar línea</Button></div>{lines.map((line, index) => <div key={index} className="grid gap-3 rounded-2xl border border-border-default p-3 md:grid-cols-[2fr_1fr_1fr_auto]"><Select id={`purchase-ingredient-${index}`} label="Ingrediente" value={line.ingredientId} options={(ingredients.data?.data ?? []).map((item) => ({ id: item.id, label: `${item.sku} · ${item.name}` }))} onChange={(value) => setLines(lines.map((current, i) => i === index ? { ...current, ingredientId: value } : current))} /><Field id={`purchase-quantity-${index}`} label="Cantidad" value={line.quantity} onChange={(value) => setLines(lines.map((current, i) => i === index ? { ...current, quantity: value } : current))} /><Field id={`purchase-cost-${index}`} label="Costo unitario" value={line.unitCost} onChange={(value) => setLines(lines.map((current, i) => i === index ? { ...current, unitCost: value } : current))} /><Button variant="ghost" className="self-end" disabled={lines.length === 1} onClick={() => setLines(lines.filter((_, i) => i !== index))} aria-label="Eliminar línea"><X className="size-4" /></Button></div>)}</div><div className="flex justify-end gap-2"><Button variant="secondary" onClick={onClose}>Cancelar</Button><Button disabled={invalid || save.isPending} onClick={() => save.mutate()}>{save.isPending ? "Guardando…" : "Guardar borrador"}</Button></div></CardContent></Card>;
}

function PurchaseOrderTable({ orders, loading, error, onRetry, onAction, onReceive }: { orders: import("@/lib/backend").RestaurantPurchaseOrderDto[]; loading: boolean; error: unknown; onRetry: () => void; onAction: (id: string, type: "submit" | "approve" | "reject") => void; onReceive: (order: import("@/lib/backend").RestaurantPurchaseOrderDto) => void }) {
  if (loading) return <AsyncState state="loading" />; if (error) return <AsyncState state="error" onRetry={onRetry} description={getApiErrorMessage(error, "No fue posible cargar las órdenes de compra.")} />;
  return <Card level={2}><CardContent className="p-5"><div className="overflow-x-auto rounded-2xl border border-border-default"><table className="w-full min-w-[950px] text-left text-sm"><thead className="bg-surface-interactive"><tr>{["Orden", "Proveedor", "Almacén", "Total", "Estado", "Recepción", "Acciones"].map((header) => <th key={header} className="px-3 py-3 font-medium">{header}</th>)}</tr></thead><tbody className="divide-y divide-border-default">{orders.length ? orders.map((order) => { const received = order.lines.reduce((sum, line) => sum + Number(line.receivedQuantity ?? 0), 0); const ordered = order.lines.reduce((sum, line) => sum + Number(line.quantity), 0); return <tr key={order.id}><td className="px-3 py-3 font-medium">{order.code}</td><td className="px-3 py-3">{order.supplierName ?? "-"}</td><td className="px-3 py-3">{order.warehouseName ?? "-"}</td><td className="px-3 py-3">{order.currency ?? "USD"} {Number(order.totalAmount ?? 0).toFixed(2)}</td><td className="px-3 py-3"><Badge>{order.status}</Badge></td><td className="px-3 py-3">{received} / {ordered}</td><td className="px-3 py-3"><span className="flex flex-wrap gap-2">{order.status === "DRAFT" ? <Button size="sm" onClick={() => onAction(order.id, "submit")}><Send className="size-4" />Enviar</Button> : null}{order.status === "PENDING_APPROVAL" ? <Button size="sm" onClick={() => onAction(order.id, "approve")}><Check className="size-4" />Aprobar</Button> : null}{["APPROVED", "SENT", "PARTIALLY_RECEIVED"].includes(order.status) ? <Button size="sm" variant="secondary" onClick={() => onReceive(order)}><Truck className="size-4" />Recibir</Button> : null}{["DRAFT", "PENDING_APPROVAL"].includes(order.status) ? <Button size="sm" variant="ghost" onClick={() => onAction(order.id, "reject")}>Rechazar</Button> : null}</span></td></tr>; }) : <tr><td colSpan={7} className="px-3 py-10 text-center text-text-secondary">No hay órdenes para el contexto actual.</td></tr>}</tbody></table></div></CardContent></Card>;
}

function PriceHistory() { const { currentBranch } = useAppStore(); const query = useQuery({ queryKey: ["restaurant-price-history", currentBranch?.id], queryFn: () => fetchRestaurantPriceHistory({ branchId: currentBranch?.id }) }); return <Card level={1}><CardContent className="space-y-4 p-5"><h2 className="font-semibold">Historial de precios por proveedor</h2><p className="text-sm text-text-secondary">Compara último costo, promedio y variación antes de crear una orden.</p><DataState query={query}>{<Table headers={["Ingrediente", "Proveedor", "Último", "Promedio", "Variación", "Última compra"]}>{(query.data ?? []).map((item) => <tr key={`${item.ingredientId}-${item.supplierId}`}><td>{item.ingredientName ?? item.ingredientId}</td><td>{item.supplierName ?? "-"}</td><td>${item.lastCost.toFixed(2)} / {item.unit ?? "unidad"}</td><td>${item.averageCost.toFixed(2)}</td><td><Badge variant={Number(item.variationPercent ?? 0) > 10 ? "destructive" : "default"}>{item.variationPercent == null ? "-" : `${item.variationPercent}%`}</Badge></td><td>{item.lastPurchasedAt ?? "-"}</td></tr>)}</Table>}</DataState></CardContent></Card>; }

function PurchaseSuggestions() { const { currentBranch } = useAppStore(); const qc = useQueryClient(); const query = useQuery({ queryKey: ["restaurant-purchase-suggestions", currentBranch?.id], queryFn: () => fetchRestaurantPurchaseSuggestions({ branchId: currentBranch?.id }) }); const convert = useMutation({ mutationFn: () => convertRestaurantPurchaseSuggestions((query.data ?? []).map((item) => ({ ingredientId: item.ingredientId, supplierId: item.supplierId, quantity: item.suggestedQuantity }))), onSuccess: () => void qc.invalidateQueries({ queryKey: ["restaurant-purchase-orders"] }) }); return <Card level={1}><CardContent className="space-y-4 p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-semibold">Sugerencias por par level y cobertura</h2><p className="text-sm text-text-secondary">La cantidad considera existencia, nivel objetivo y días de cobertura.</p></div><Button disabled={!query.data?.length || convert.isPending} onClick={() => convert.mutate()}><Plus className="size-4" />Convertir en orden</Button></div>{convert.error ? <InlineFeedback tone="danger" title="No se pudo convertir">{getApiErrorMessage(convert.error, "El backend no pudo crear la orden.")}</InlineFeedback> : null}<DataState query={query}>{<Table headers={["Ingrediente", "Proveedor", "Stock", "Par", "Cobertura", "Sugerido", "Motivo"]}>{(query.data ?? []).map((item) => <tr key={item.ingredientId}><td>{item.ingredientName ?? item.ingredientId}</td><td>{item.supplierName ?? "-"}</td><td>{item.currentStock} {item.unit}</td><td>{item.parLevel} {item.unit}</td><td>{item.coverageDays} / {item.targetCoverageDays} días</td><td className="font-semibold">{item.suggestedQuantity} {item.unit}</td><td>{item.reason}</td></tr>)}</Table>}</DataState></CardContent></Card>; }

function InvoiceInbox() { const { currentBranch } = useAppStore(); const { warehouseId } = useRestaurantInventoryContext(); const qc = useQueryClient(); const query = useQuery({ queryKey: ["restaurant-invoices", currentBranch?.id, warehouseId], queryFn: () => fetchRestaurantInvoices({ branchId: currentBranch?.id, warehouseId }) }); const upload = useMutation({ mutationFn: (file: File) => currentBranch?.id && warehouseId ? uploadRestaurantInvoice(file, { branchId: currentBranch.id, warehouseId }) : Promise.reject(new Error("Selecciona sucursal y almacén")), onSuccess: () => void qc.invalidateQueries({ queryKey: ["restaurant-invoices"] }) }); const process = useMutation({ mutationFn: (id: string) => processRestaurantInvoice(id), onSuccess: () => void qc.invalidateQueries({ queryKey: ["restaurant-invoices"] }) }); return <Card level={1}><CardContent className="space-y-4 p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-semibold">Bandeja de facturas OCR</h2><p className="text-sm text-text-secondary">Carga facturas para extracción y revisión antes de conciliarlas con una orden.</p></div><label className="inline-flex cursor-pointer items-center gap-2"><Button asChild variant="secondary"><span><FileUp className="size-4" />Subir factura</span></Button><input className="sr-only" type="file" accept=".pdf,.jpg,.jpeg,.png" onChange={(event) => { const file = event.target.files?.[0]; if (file) upload.mutate(file); }} /></label></div>{upload.error || process.error ? <InlineFeedback tone="danger" title="No se pudo procesar la factura">{getApiErrorMessage(upload.error ?? process.error, "Revisa el contexto y el archivo.")}</InlineFeedback> : null}<DataState query={query}>{<Table headers={["Archivo", "Proveedor", "Factura", "Confianza", "Total", "Estado", "Acciones"]}>{(query.data ?? []).map((item) => <tr key={item.id}><td>{item.fileName}</td><td>{item.supplierName ?? "-"}</td><td>{item.invoiceNumber ?? "Pendiente"}</td><td>{item.confidence == null ? "-" : `${item.confidence}%`}</td><td>{item.total == null ? "-" : `$${item.total.toFixed(2)}`}</td><td><Badge>{item.status}</Badge></td><td>{["UPLOADED", "FAILED"].includes(item.status) ? <Button size="sm" onClick={() => process.mutate(item.id)}>Procesar OCR</Button> : null}</td></tr>)}</Table>}</DataState></CardContent></Card>; }

function DataState({ query, children }: { query: { isLoading: boolean; error: unknown; refetch: () => unknown }; children: React.ReactNode }) { if (query.isLoading) return <AsyncState state="loading" />; if (query.error) return <AsyncState state="error" onRetry={() => void query.refetch()} description={getApiErrorMessage(query.error, "El endpoint comercial aún no está disponible.")} />; return <>{children}</>; }
function Table({ headers, children }: { headers: string[]; children: React.ReactNode }) { return <div className="overflow-x-auto rounded-2xl border border-border-default"><table className="w-full min-w-[850px] text-left text-sm"><thead className="bg-surface-interactive"><tr>{headers.map((header) => <th key={header} className="px-3 py-3 font-medium">{header}</th>)}</tr></thead><tbody className="divide-y divide-border-default">{children}</tbody></table></div>; }
function Select({ id, label, value, options, onChange }: { id: string; label: string; value: string; options: Array<{ id: string; label: string }>; onChange: (value: string) => void }) { return <div><Label htmlFor={id}>{label}</Label><select id={id} className="mt-1 h-11 w-full rounded-2xl border border-border-default bg-surface-elevated px-3" value={value} onChange={(event) => onChange(event.target.value)}><option value="">Seleccionar</option>{options.map((option) => <option key={option.id} value={option.id}>{option.label}</option>)}</select></div>; }
function Field({ id, label, value, onChange }: { id: string; label: string; value: string; onChange: (value: string) => void }) { return <div><Label htmlFor={id}>{label}</Label><Input id={id} type="number" min="0" step="0.01" value={value} onChange={(event) => onChange(event.target.value)} /></div>; }
