"use client";

import { useState, type ReactNode } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { BarChart3, Building2, Calculator, Factory, Plus, TrendingUp } from "lucide-react";
import {
  createRestaurantCommissary,
  createRestaurantPurchaseBudget,
  fetchRestaurantBranchCosts,
  fetchRestaurantCommissaries,
  fetchRestaurantDemandForecast,
  fetchRestaurantPurchaseBudgets,
  fetchRestaurantRecipeMargins,
  fetchRestaurantUnitComparison,
  getApiErrorMessage,
} from "@/lib/backend";
import { useAppStore } from "@/store/app-store";
import { useRestaurantInventoryContext } from "@/components/restaurant-inventory-context";
import { AsyncState } from "@/components/async-state";
import { InlineFeedback, PageHeader } from "@/components/design-system";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";

type View = "forecast" | "branches" | "margins" | "comparison" | "commissary" | "budget";

export function RestaurantCommercialIntelligenceWorkspace({ initialView = "forecast" }: { initialView?: View }) {
  const [view, setView] = useState<View>(initialView);
  const tabs: Array<{ id: View; label: string; icon: typeof TrendingUp }> = [
    { id: "forecast", label: "Pronóstico", icon: TrendingUp },
    { id: "branches", label: "Costos por sucursal", icon: Building2 },
    { id: "margins", label: "Margen por receta", icon: Calculator },
    { id: "comparison", label: "Comparativo multiunidad", icon: BarChart3 },
    { id: "commissary", label: "Comisariato", icon: Factory },
    { id: "budget", label: "Presupuesto de compras", icon: Calculator },
  ];
  return <div className="space-y-5"><PageHeader eyebrow="Inteligencia comercial" title="Decisiones comerciales de inventario" description="Pronostica demanda, controla costos, compara unidades y protege el presupuesto de compras." /><nav className="flex flex-wrap gap-2" aria-label="Inteligencia comercial">{tabs.map(({ id, label, icon: Icon }) => <Button key={id} variant={view === id ? "default" : "secondary"} onClick={() => setView(id)}><Icon className="size-4" />{label}</Button>)}</nav>{view === "forecast" ? <ForecastView /> : null}{view === "branches" ? <BranchCostsView /> : null}{view === "margins" ? <RecipeMarginsView /> : null}{view === "comparison" ? <UnitComparisonView /> : null}{view === "commissary" ? <CommissaryView /> : null}{view === "budget" ? <BudgetView /> : null}</div>;
}

function CommercialCard({ title, description, children }: { title: string; description: string; children: ReactNode }) { return <Card level={1}><CardContent className="space-y-4 p-5"><div><h2 className="font-semibold">{title}</h2><p className="text-sm text-text-secondary">{description}</p></div>{children}</CardContent></Card>; }
function QueryState({ query, children }: { query: { isLoading: boolean; error: unknown; refetch: () => unknown }; children: ReactNode }) { if (query.isLoading) return <AsyncState state="loading" />; if (query.error) return <AsyncState state="error" onRetry={() => void query.refetch()} description={getApiErrorMessage(query.error, "El contrato de inteligencia comercial aún no está disponible.")} />; return <>{children}</>; }
function Table({ headers, children }: { headers: string[]; children: ReactNode }) { return <div className="overflow-x-auto rounded-2xl border border-border-default"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-surface-interactive"><tr>{headers.map((header) => <th key={header} className="px-3 py-3 font-medium">{header}</th>)}</tr></thead><tbody className="divide-y divide-border-default">{children}</tbody></table></div>; }

function CommercialFilters() { const { currentBranch } = useAppStore(); const { warehouseId } = useRestaurantInventoryContext(); return <div className="flex flex-wrap gap-2 text-sm text-text-secondary"><Badge variant="secondary">Sucursal: {currentBranch?.name ?? "Todas"}</Badge><Badge variant="secondary">Almacén: {warehouseId ? "Seleccionado" : "Todos"}</Badge></div>; }
function ForecastView() { const { currentBranch } = useAppStore(); const { warehouseId } = useRestaurantInventoryContext(); const query = useQuery({ queryKey: ["restaurant-demand-forecast", currentBranch?.id, warehouseId], queryFn: () => fetchRestaurantDemandForecast({ branchId: currentBranch?.id, warehouseId, horizon: 30 }) }); return <CommercialCard title="Pronóstico de demanda" description="Proyección de consumo para anticipar compras y reducir quiebres o sobreinventario."><CommercialFilters /><QueryState query={query}><Table headers={["Periodo", "Ingrediente", "Pronóstico", "Rango", "Confianza"]}>{(query.data ?? []).map((item, index) => <tr key={`${item.period}-${item.ingredientId ?? index}`}><td>{item.period}</td><td>{item.ingredientName ?? item.ingredientId ?? "-"}</td><td>{item.predictedQuantity} {item.unit ?? ""}</td><td>{item.lowerBound ?? "-"} - {item.upperBound ?? "-"}</td><td>{item.confidence == null ? "-" : `${item.confidence.toFixed(0)}%`}</td></tr>)}</Table></QueryState></CommercialCard>; }
function BranchCostsView() { const query = useQuery({ queryKey: ["restaurant-branch-costs"], queryFn: () => fetchRestaurantBranchCosts() }); return <CommercialCard title="Costos por sucursal" description="Compara compras, consumo, inventario y food cost por unidad operativa."><QueryState query={query}><Table headers={["Sucursal", "Periodo", "Compras", "Consumo", "Inventario", "Food cost", "Variación"]}>{(query.data ?? []).map((item) => <tr key={`${item.branchId}-${item.period}`}><td>{item.branchName}</td><td>{item.period}</td><td>${item.purchaseCost.toFixed(2)}</td><td>${item.consumptionCost.toFixed(2)}</td><td>${item.inventoryCost.toFixed(2)}</td><td>{item.foodCostPercent == null ? "-" : `${item.foodCostPercent.toFixed(1)}%`}</td><td>${(item.varianceCost ?? 0).toFixed(2)}</td></tr>)}</Table></QueryState></CommercialCard>; }
function RecipeMarginsView() { const query = useQuery({ queryKey: ["restaurant-recipe-margins"], queryFn: () => fetchRestaurantRecipeMargins() }); return <CommercialCard title="Margen por receta y periodo" description="Identifica recetas rentables y aquellas cuyo costo está erosionando el margen."><QueryState query={query}><Table headers={["Receta", "Periodo", "Porciones", "Ingresos", "Costo", "Margen", "% margen"]}>{(query.data ?? []).map((item) => <tr key={`${item.recipeId}-${item.period}`}><td>{item.recipeName}</td><td>{item.period}</td><td>{item.portions}</td><td>${item.revenue.toFixed(2)}</td><td>${item.cost.toFixed(2)}</td><td>${item.margin.toFixed(2)}</td><td><Badge variant={item.marginPercent < 20 ? "destructive" : "default"}>{item.marginPercent.toFixed(1)}%</Badge></td></tr>)}</Table></QueryState></CommercialCard>; }
function UnitComparisonView() { const query = useQuery({ queryKey: ["restaurant-unit-comparison"], queryFn: () => fetchRestaurantUnitComparison() }); return <CommercialCard title="Comparativo multiunidad" description="Observa indicadores equivalentes entre sucursales para detectar mejores prácticas y desviaciones."><QueryState query={query}><Table headers={["Métrica", "Unidad", "Periodo", "Valor", "Ranking", "Cambio"]}>{(query.data ?? []).map((item, index) => <tr key={`${item.metric}-${item.unit}-${index}`}><td>{item.metric}</td><td>{item.unit}</td><td>{item.period}</td><td>{item.value.toFixed(2)}</td><td>{item.rank ?? "-"}</td><td>{item.changePercent == null ? "-" : `${item.changePercent.toFixed(1)}%`}</td></tr>)}</Table></QueryState></CommercialCard>; }

function CommissaryView() { const query = useQuery({ queryKey: ["restaurant-commissaries"], queryFn: () => fetchRestaurantCommissaries() }); const qc = useQueryClient(); const [name, setName] = useState(""); const create = useMutation({ mutationFn: () => createRestaurantCommissary({ name, code: name.toUpperCase().replace(/\s+/g, "-") }), onSuccess: () => { setName(""); void qc.invalidateQueries({ queryKey: ["restaurant-commissaries"] }); } }); return <CommercialCard title="Comisariato" description="Centraliza producción, abastecimiento y distribución interna entre sucursales."><div className="grid gap-3 sm:grid-cols-[1fr_auto]"><div><Label htmlFor="commissary-name">Nuevo comisariato</Label><Input id="commissary-name" value={name} onChange={(event) => setName(event.target.value)} placeholder="Cocina central" /></div><Button className="self-end" disabled={!name.trim() || create.isPending} onClick={() => create.mutate()}><Plus className="size-4" />Crear</Button></div>{create.error ? <InlineFeedback tone="danger" title="No se pudo crear">{getApiErrorMessage(create.error, "Revisa los datos del comisariato.")}</InlineFeedback> : null}<QueryState query={query}><Table headers={["Código", "Nombre", "Estado", "Sucursales", "Ítems", "Valor"]}>{(query.data ?? []).map((item) => <tr key={item.id}><td>{item.code}</td><td>{item.name}</td><td><Badge>{item.status}</Badge></td><td>{item.branchCount}</td><td>{item.itemsCount ?? "-"}</td><td>{item.totalValue == null ? "-" : `$${item.totalValue.toFixed(2)}`}</td></tr>)}</Table></QueryState></CommercialCard>; }
function BudgetView() { const query = useQuery({ queryKey: ["restaurant-purchase-budgets"], queryFn: () => fetchRestaurantPurchaseBudgets() }); const qc = useQueryClient(); const [period, setPeriod] = useState(""); const [budget, setBudget] = useState(""); const create = useMutation({ mutationFn: () => createRestaurantPurchaseBudget({ period, budget: Number(budget) }), onSuccess: () => { setPeriod(""); setBudget(""); void qc.invalidateQueries({ queryKey: ["restaurant-purchase-budgets"] }); } }); return <CommercialCard title="Presupuesto y control de compras" description="Controla presupuesto, comprometido, recibido y disponible antes de confirmar compras."><div className="grid gap-3 sm:grid-cols-[1fr_1fr_auto]"><div><Label htmlFor="budget-period">Periodo</Label><Input id="budget-period" type="month" value={period} onChange={(event) => setPeriod(event.target.value)} /></div><div><Label htmlFor="budget-amount">Presupuesto</Label><Input id="budget-amount" type="number" min="0" value={budget} onChange={(event) => setBudget(event.target.value)} /></div><Button className="self-end" disabled={!period || !budget || create.isPending} onClick={() => create.mutate()}>Guardar presupuesto</Button></div>{create.error ? <InlineFeedback tone="danger" title="No se pudo guardar">{getApiErrorMessage(create.error, "Revisa el periodo y el importe.")}</InlineFeedback> : null}<QueryState query={query}><Table headers={["Periodo", "Sucursal", "Presupuesto", "Comprometido", "Recibido", "Disponible", "Uso"]}>{(query.data ?? []).map((item) => <tr key={item.id}><td>{item.period}</td><td>{item.branchName ?? "Todas"}</td><td>${item.budget.toFixed(2)}</td><td>${item.committed.toFixed(2)}</td><td>${item.received.toFixed(2)}</td><td>${item.remaining.toFixed(2)}</td><td><Badge variant={item.utilizationPercent > 100 ? "destructive" : "default"}>{item.utilizationPercent.toFixed(1)}%</Badge></td></tr>)}</Table></QueryState></CommercialCard>; }
