"use client";

import { useState } from "react";
import { Check, ChevronLeft, ChevronRight, Plus, Trash2 } from "lucide-react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { confirmRestaurantProduction, createRestaurantProduction, fetchRestaurantProductions, getApiErrorMessage, previewRestaurantProduction } from "@/lib/backend";
import { AsyncState } from "@/components/async-state";
import { InlineFeedback, PageHeader } from "@/components/design-system";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";

type RecipeOption = { id: string; label: string };
type ProductionLine = { recipeId: string; plannedQuantity: string; actualYield: string };
type ProductionPreview = Awaited<ReturnType<typeof previewRestaurantProduction>>;
type ProductionIngredient = ProductionPreview["ingredients"][number];
const stages = ["Receta", "Cantidad", "Ingredientes requeridos", "Existencias", "Confirmar"];

export function RestaurantProductionWorkflow({ branchId, warehouseId, recipeOptions, canManage }: { branchId: string; warehouseId?: string; recipeOptions: RecipeOption[]; canManage: boolean }) {
  const queryClient = useQueryClient();
  const [stage, setStage] = useState(1);
  const [lines, setLines] = useState<ProductionLine[]>([{ recipeId: "", plannedQuantity: "1", actualYield: "1" }]);
  const [previews, setPreviews] = useState<ProductionPreview[]>([]);
  const [justification, setJustification] = useState("");
  const preview = useMutation({ mutationFn: async () => Promise.all(lines.map((line) => previewRestaurantProduction({ branchId, warehouseId, recipeId: line.recipeId, plannedQuantity: Number(line.plannedQuantity), actualYield: Number(line.actualYield), productionDate: new Date().toISOString() }))), onSuccess: (data) => { setPreviews(data); setStage(4); } });
  const confirm = useMutation({ mutationFn: async () => { const created: Array<{ id: string }> = []; for (const line of lines) { const draft = await createRestaurantProduction({ branchId, warehouseId, recipeId: line.recipeId, plannedQuantity: Number(line.plannedQuantity), actualYield: Number(line.actualYield), productionDate: new Date().toISOString(), justification: justification || undefined }); const confirmed = await confirmRestaurantProduction(draft.id); created.push(confirmed); } return created; }, onSuccess: async () => { setLines([{ recipeId: "", plannedQuantity: "1", actualYield: "1" }]); setPreviews([]); setJustification(""); setStage(1); await Promise.all([queryClient.invalidateQueries({ queryKey: ["restaurant-stock"] }), queryClient.invalidateQueries({ queryKey: ["restaurant-dashboard"] }), queryClient.invalidateQueries({ queryKey: ["restaurant-movements"] }), queryClient.invalidateQueries({ queryKey: ["restaurant-productions"] }), queryClient.invalidateQueries({ queryKey: ["restaurant-phase2-dashboard"] }), queryClient.invalidateQueries({ queryKey: ["restaurant-recipes"] }), queryClient.invalidateQueries({ queryKey: ["restaurant-recipe-cost"] })]); } });
  const pending = useQuery({ queryKey: ["restaurant-productions", branchId, "pending"], queryFn: async () => (await fetchRestaurantProductions({ branchId })).filter((item) => ["DRAFT", "PENDING", "IN_PROGRESS"].includes(item.status)) });
  const shortages = previews.flatMap((item) => item.ingredients.filter((ingredient) => !ingredient.sufficient));
  const valid = Boolean(warehouseId) && lines.length > 0 && lines.every((line) => line.recipeId && Number(line.plannedQuantity) > 0 && Number(line.actualYield) > 0);
  const next = () => { if (stage === 3) { if (valid) preview.mutate(); return; } if (stage < 5) setStage((value) => value + 1); };
  const previous = () => setStage((value) => Math.max(1, value - 1));
  return <div className="space-y-5"><PageHeader eyebrow="Producción" title="Producción pendiente y nueva operación" description="Planifica varias recetas, compara existencias y confirma todos los documentos en una sola operación." />{!warehouseId ? <InlineFeedback tone="warning" title="Almacén requerido">Selecciona un almacén global antes de planificar producción.</InlineFeedback> : null}{preview.error || confirm.error ? <InlineFeedback tone="danger" title="No se pudo completar la producción">{getApiErrorMessage(preview.error ?? confirm.error, "Revisa las recetas y existencias.")}</InlineFeedback> : null}<Card level={1}><CardContent className="space-y-4 p-5"><div className="grid gap-2 sm:grid-cols-5" aria-label="Flujo de producción">{stages.map((label, index) => { const number = index + 1; return <button key={label} type="button" onClick={() => number <= stage && setStage(number)} className={`rounded-xl border p-3 text-left text-xs font-semibold ${stage === number ? "border-primary bg-primary/10" : number < stage ? "border-success/40 bg-success/5" : "border-border-default"}`}><span className="grid size-6 place-items-center rounded-full bg-surface-interactive">{number < stage ? <Check className="size-3" /> : number}</span><span className="mt-2 block">{label}</span></button>; })}</div>{stage === 1 ? <RecipeStage lines={lines} recipeOptions={recipeOptions} setLines={setLines} /> : null}{stage === 2 ? <QuantityStage lines={lines} setLines={setLines} recipeOptions={recipeOptions} /> : null}{stage === 3 ? <RequiredStage lines={lines} recipeOptions={recipeOptions} /> : null}{stage === 4 ? <AvailabilityStage previews={previews} recipeOptions={recipeOptions} shortages={shortages} /> : null}{stage === 5 ? <ConfirmStage previews={previews} shortages={shortages} justification={justification} setJustification={setJustification} /> : null}<div className="flex justify-between gap-2 border-t border-border-default pt-4"><Button variant="secondary" disabled={stage === 1 || preview.isPending || confirm.isPending} onClick={previous}><ChevronLeft className="size-4" />Anterior</Button>{stage < 3 ? <Button disabled={!valid} onClick={next}>Siguiente<ChevronRight className="size-4" /></Button> : stage === 3 ? <Button disabled={!valid || preview.isPending} onClick={next}>{preview.isPending ? "Calculando…" : "Comparar existencias"}<ChevronRight className="size-4" /></Button> : stage === 4 ? <Button disabled={!previews.length} onClick={() => setStage(5)}>Revisar confirmación<ChevronRight className="size-4" /></Button> : <Button disabled={!canManage || !previews.length || confirm.isPending || (shortages.length > 0 && justification.trim().length < 10)} onClick={() => confirm.mutate()}>{confirm.isPending ? "Confirmando…" : "Confirmar producción"}</Button>}</div></CardContent></Card><PendingProductionInbox query={pending} /></div>;
}

function RecipeStage({ lines, recipeOptions, setLines }: { lines: ProductionLine[]; recipeOptions: RecipeOption[]; setLines: (lines: ProductionLine[]) => void }) { return <section className="space-y-4"><div><h2 className="font-semibold">1. Seleccionar recetas</h2><p className="text-sm text-text-secondary">Puedes agrupar varias recetas en una misma operación.</p></div>{lines.map((line, index) => <div key={index} className="flex flex-wrap items-end gap-3 rounded-2xl border border-border-default p-3"><div className="min-w-[260px] flex-1"><Select id={`production-recipe-${index}`} label={`Receta ${index + 1}`} value={line.recipeId} options={recipeOptions} onChange={(value) => setLines(lines.map((current, i) => i === index ? { ...current, recipeId: value } : current))} /></div>{lines.length > 1 ? <Button variant="ghost" onClick={() => setLines(lines.filter((_, i) => i !== index))} aria-label="Eliminar receta"><Trash2 className="size-4" /></Button> : null}</div>)}<Button size="sm" variant="secondary" onClick={() => setLines([...lines, { recipeId: "", plannedQuantity: "1", actualYield: "1" }])}><Plus className="size-4" />Agregar otra receta</Button></section>; }
function QuantityStage({ lines, recipeOptions, setLines }: { lines: ProductionLine[]; recipeOptions: RecipeOption[]; setLines: (lines: ProductionLine[]) => void }) { return <section className="space-y-4"><div><h2 className="font-semibold">2. Definir cantidad</h2><p className="text-sm text-text-secondary">Indica la cantidad planificada y el rendimiento real esperado.</p></div>{lines.map((line, index) => <div key={index} className="grid gap-3 rounded-2xl border border-border-default p-3 sm:grid-cols-[2fr_1fr_1fr]"><p className="flex items-center font-medium">{recipeOptions.find((item) => item.id === line.recipeId)?.label ?? "Receta pendiente"}</p><Field id={`production-planned-${index}`} label="Cantidad planificada" value={line.plannedQuantity} onChange={(value) => setLines(lines.map((current, i) => i === index ? { ...current, plannedQuantity: value } : current))} /><Field id={`production-yield-${index}`} label="Rendimiento real" value={line.actualYield} onChange={(value) => setLines(lines.map((current, i) => i === index ? { ...current, actualYield: value } : current))} /></div>)}</section>; }
function RequiredStage({ lines, recipeOptions }: { lines: ProductionLine[]; recipeOptions: RecipeOption[] }) { return <section className="space-y-4"><h2 className="font-semibold">3. Ingredientes requeridos</h2>{lines.map((line, index) => <div key={index} className="rounded-2xl border border-border-default p-4"><p className="font-medium">{recipeOptions.find((item) => item.id === line.recipeId)?.label ?? "Receta"}</p><p className="mt-2 text-sm text-text-secondary">El backend calculará cantidades, conversiones y costo al comparar existencias.</p></div>)}</section>; }
function AvailabilityStage({ previews, recipeOptions, shortages }: { previews: ProductionPreview[]; recipeOptions: RecipeOption[]; shortages: ProductionIngredient[] }) { return <section className="space-y-4"><div><h2 className="font-semibold">4. Comparar existencia disponible</h2><p className="text-sm text-text-secondary">Revisa cada ingrediente antes de confirmar.</p></div>{shortages.length ? <InlineFeedback tone="warning" title={`${shortages.length} faltantes detectados`}>Puedes continuar sólo con una justificación de al menos 10 caracteres si el permiso de override está habilitado.</InlineFeedback> : <InlineFeedback tone="success" title="Existencias suficientes">No se detectaron faltantes en la vista previa.</InlineFeedback>}<div className="space-y-4">{previews.map((preview, index) => <Card key={`${preview.id}-${index}`} level={2}><CardContent className="p-4"><h3 className="font-medium">{preview.preparationName || recipeOptions[index]?.label}</h3><IngredientTable ingredients={preview.ingredients} /></CardContent></Card>)}</div></section>; }
function ConfirmStage({ previews, shortages, justification, setJustification }: { previews: ProductionPreview[]; shortages: ProductionIngredient[]; justification: string; setJustification: (value: string) => void }) { return <section className="space-y-4"><h2 className="font-semibold">5. Confirmar producción</h2><div className="grid gap-3 sm:grid-cols-3"><Metric label="Recetas" value={previews.length} /><Metric label="Costo consumido" value={`$${previews.reduce((total, item) => total + item.consumedCost, 0).toFixed(2)}`} /><Metric label="Faltantes" value={shortages.length} /></div>{shortages.length ? <div><Label htmlFor="production-justification">Justificación de faltantes</Label><Input id="production-justification" value={justification} onChange={(event) => setJustification(event.target.value)} placeholder="Mínimo 10 caracteres" /></div> : null}<InlineFeedback tone="warning" title="Acción irreversible">Confirmar creará y aplicará los movimientos de todas las recetas seleccionadas.</InlineFeedback></section>; }
function IngredientTable({ ingredients }: { ingredients: ProductionIngredient[] }) { return <div className="mt-3 overflow-x-auto rounded-xl border border-border-default"><table className="w-full min-w-[620px] text-left text-sm"><thead className="bg-surface-interactive"><tr>{["Ingrediente", "Requerido", "Disponible", "Unidad", "Estado"].map((header) => <th key={header} className="px-3 py-2">{header}</th>)}</tr></thead><tbody className="divide-y divide-border-default">{ingredients.map((ingredient) => <tr key={`${ingredient.ingredientName}-${ingredient.unit}`}><td className="px-3 py-2">{ingredient.ingredientName}</td><td className="px-3 py-2">{ingredient.requiredQuantity}</td><td className="px-3 py-2">{ingredient.availableQuantity}</td><td className="px-3 py-2">{ingredient.unit}</td><td className="px-3 py-2"><Badge variant={ingredient.sufficient ? "default" : "destructive"}>{ingredient.sufficient ? "Disponible" : "Faltante"}</Badge></td></tr>)}</tbody></table></div>; }
function PendingProductionInbox({ query }: { query: ReturnType<typeof useQuery<import("@/lib/contracts").RestaurantProductionDto[]>> }) { if (query.isLoading) return <AsyncState state="loading" />; if (query.error) return <AsyncState state="error" onRetry={() => void query.refetch()} description={getApiErrorMessage(query.error, "No fue posible cargar la producción pendiente.")} />; return <Card level={1}><CardContent className="space-y-3 p-5"><div className="flex items-center justify-between"><div><h2 className="font-semibold">Producción pendiente</h2><p className="text-sm text-text-secondary">Documentos en borrador que todavía no actualizan existencias.</p></div><Badge variant="secondary">{query.data?.length ?? 0}</Badge></div>{query.data?.length ? <div className="space-y-2">{query.data.map((item) => <div key={item.id} className="flex flex-wrap justify-between gap-3 rounded-xl border border-border-default p-3"><span><strong>{item.preparationName}</strong> · {item.plannedQuantity} planificadas · ${item.consumedCost.toFixed(2)}</span><Badge>{item.status}</Badge></div>)}</div> : <p className="text-sm text-text-secondary">No hay producciones pendientes.</p>}</CardContent></Card>; }
function Select({ id, label, value, options, onChange }: { id: string; label: string; value: string; options: RecipeOption[]; onChange: (value: string) => void }) { return <div><Label htmlFor={id}>{label}</Label><select id={id} className="h-11 w-full rounded-2xl border border-border-default bg-surface-elevated px-3" value={value} onChange={(event) => onChange(event.target.value)}><option value="">Seleccionar</option>{options.map((option) => <option key={option.id} value={option.id}>{option.label}</option>)}</select></div>; }
function Field({ id, label, value, onChange }: { id: string; label: string; value: string; onChange: (value: string) => void }) { return <div><Label htmlFor={id}>{label}</Label><Input id={id} type="number" min="0.01" step="0.01" value={value} onChange={(event) => onChange(event.target.value)} /></div>; }
function Metric({ label, value }: { label: string; value: string | number }) { return <div className="rounded-xl border border-border-default bg-surface-interactive p-3"><p className="text-xs text-text-secondary">{label}</p><p className="mt-1 font-semibold">{value}</p></div>; }
