"use client";

import { useState } from "react";
import { Check, CalendarClock } from "lucide-react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { acknowledgeRestaurantExpiryAlert, createRestaurantCountSchedule, fetchRestaurantAuditLog, fetchRestaurantCountSchedules, fetchRestaurantExpiryAlerts, fetchRestaurantShrinkageAlerts, fetchRestaurantVariance, getApiErrorMessage } from "@/lib/backend";
import { useAppStore } from "@/store/app-store";
import { useRestaurantInventoryContext } from "@/components/restaurant-inventory-context";
import { AsyncState } from "@/components/async-state";
import { InlineFeedback, PageHeader } from "@/components/design-system";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";

type View = "fefo" | "counts" | "variance" | "shrinkage" | "audit";

export function RestaurantAdvancedControlWorkspace({ initialView = "fefo" }: { initialView?: View }) {
  const [view, setView] = useState<View>(initialView);
  return <div className="space-y-5"><PageHeader eyebrow="Control avanzado" title="Control avanzado de inventario" description="FEFO, vencimientos, conteos programados, variación y auditoría inmutable." /><nav className="flex flex-wrap gap-2" aria-label="Control avanzado"><Button variant={view === "fefo" ? "default" : "secondary"} onClick={() => setView("fefo")}>FEFO y vencimientos</Button><Button variant={view === "counts" ? "default" : "secondary"} onClick={() => setView("counts")}>Conteos programados</Button><Button variant={view === "variance" ? "default" : "secondary"} onClick={() => setView("variance")}>Teórico vs real</Button><Button variant={view === "shrinkage" ? "default" : "secondary"} onClick={() => setView("shrinkage")}>Shrinkage</Button><Button variant={view === "audit" ? "default" : "secondary"} onClick={() => setView("audit")}>Auditoría inmutable</Button></nav>{view === "fefo" ? <FefoView /> : null}{view === "counts" ? <CountScheduleView /> : null}{view === "variance" ? <VarianceView /> : null}{view === "shrinkage" ? <ShrinkageView /> : null}{view === "audit" ? <AuditView /> : null}</div>;
}

function FefoView() { const { currentBranch } = useAppStore(); const { warehouseId } = useRestaurantInventoryContext(); const qc = useQueryClient(); const query = useQuery({ queryKey: ["restaurant-expiry-alerts", currentBranch?.id, warehouseId], queryFn: () => fetchRestaurantExpiryAlerts({ branchId: currentBranch?.id, warehouseId, sort: "expirationDate" }) }); const acknowledge = useMutation({ mutationFn: (id: string) => acknowledgeRestaurantExpiryAlert(id), onSuccess: () => void qc.invalidateQueries({ queryKey: ["restaurant-expiry-alerts"] }) }); return <Card level={1}><CardContent className="space-y-4 p-5"><div><h2 className="font-semibold">FEFO y alertas de vencimiento</h2><p className="text-sm text-text-secondary">Prioriza el lote con vencimiento más próximo y evita consumir lotes posteriores antes de tiempo.</p></div><DataState query={query}>{<Table headers={["Ingrediente", "Lote", "Vence", "Días", "Cantidad", "Severidad", "Acción"]}>{(query.data ?? []).map((item) => <tr key={item.id}><td>{item.ingredientName ?? item.ingredientId}</td><td>{item.lotNumber ?? "-"}</td><td>{item.expirationDate}</td><td>{item.daysRemaining}</td><td>{item.quantity} {item.unit}</td><td><Badge variant={item.severity === "EXPIRED" || item.severity === "CRITICAL" ? "destructive" : item.severity === "WARNING" ? "secondary" : "default"}>{item.severity}</Badge></td><td>{item.acknowledged ? <Badge variant="secondary">Atendida</Badge> : <Button size="sm" variant="secondary" onClick={() => acknowledge.mutate(item.id)}><Check className="size-4" />Atender</Button>}</td></tr>)}</Table>}</DataState></CardContent></Card>; }

function CountScheduleView() { const { currentBranch } = useAppStore(); const { warehouseId } = useRestaurantInventoryContext(); const qc = useQueryClient(); const query = useQuery({ queryKey: ["restaurant-count-schedules", currentBranch?.id, warehouseId], queryFn: () => fetchRestaurantCountSchedules({ branchId: currentBranch?.id, warehouseId }) }); const [frequency, setFrequency] = useState("WEEKLY"); const [nextRun, setNextRun] = useState(""); const create = useMutation({ mutationFn: () => createRestaurantCountSchedule({ branchId: currentBranch?.id, warehouseId, frequency, nextRun, partial: true }), onSuccess: () => void qc.invalidateQueries({ queryKey: ["restaurant-count-schedules"] }) }); return <div className="space-y-4"><Card level={1}><CardContent className="space-y-4 p-5"><div><h2 className="font-semibold">Conteo parcial y programado</h2><p className="text-sm text-text-secondary">Programa conteos por zona o ingredientes críticos sin bloquear toda la operación.</p></div><div className="grid gap-3 sm:grid-cols-3"><div><Label htmlFor="count-frequency">Frecuencia</Label><select id="count-frequency" className="mt-1 h-11 w-full rounded-2xl border border-border-default bg-surface-elevated px-3" value={frequency} onChange={(event) => setFrequency(event.target.value)}><option value="DAILY">Diario</option><option value="WEEKLY">Semanal</option><option value="MONTHLY">Mensual</option></select></div><div><Label htmlFor="count-next-run">Próximo conteo</Label><Input id="count-next-run" type="date" value={nextRun} onChange={(event) => setNextRun(event.target.value)} /></div><Button className="self-end" disabled={!warehouseId || !nextRun || create.isPending} onClick={() => create.mutate()}><CalendarClock className="size-4" />Programar conteo</Button></div>{create.error ? <InlineFeedback tone="danger" title="No se pudo programar">{getApiErrorMessage(create.error, "El backend no pudo guardar la programación.")}</InlineFeedback> : null}</CardContent></Card><Card level={2}><CardContent className="space-y-3 p-5"><h3 className="font-semibold">Programaciones activas</h3><DataState query={query}>{<Table headers={["Frecuencia", "Próxima ejecución", "Modo", "Estado"]}>{(query.data ?? []).map((item, index) => <tr key={String(item.id ?? index)}><td>{String(item.frequency ?? "-")}</td><td>{String(item.nextRun ?? "-")}</td><td>{item.partial ? "Parcial" : "Completo"}</td><td><Badge>{String(item.status ?? "ACTIVE")}</Badge></td></tr>)}</Table>}</DataState></CardContent></Card></div>; }

function VarianceView() { const { currentBranch } = useAppStore(); const { warehouseId } = useRestaurantInventoryContext(); const query = useQuery({ queryKey: ["restaurant-variance", currentBranch?.id, warehouseId], queryFn: () => fetchRestaurantVariance({ branchId: currentBranch?.id, warehouseId }) }); return <Card level={1}><CardContent className="space-y-4 p-5"><div><h2 className="font-semibold">Variación actual versus teórica</h2><p className="text-sm text-text-secondary">Compara consumo esperado por recetas contra consumo real y costo observado.</p></div><DataState query={query}>{<Table headers={["Ingrediente", "Teórico", "Real", "Variación", "Costo teórico", "Costo real", "Impacto"]}>{(query.data ?? []).map((item) => <tr key={item.ingredientId}><td>{item.ingredientName ?? item.ingredientId}</td><td>{item.theoreticalQuantity}</td><td>{item.actualQuantity}</td><td><Badge variant={Math.abs(item.variancePercent) > 5 ? "destructive" : "default"}>{item.variancePercent.toFixed(1)}%</Badge></td><td>${item.theoreticalCost.toFixed(2)}</td><td>${item.actualCost.toFixed(2)}</td><td>${item.varianceCost.toFixed(2)}</td></tr>)}</Table>}</DataState></CardContent></Card>; }

function ShrinkageView() { const { currentBranch } = useAppStore(); const { warehouseId } = useRestaurantInventoryContext(); const query = useQuery({ queryKey: ["restaurant-shrinkage", currentBranch?.id, warehouseId], queryFn: () => fetchRestaurantShrinkageAlerts({ branchId: currentBranch?.id, warehouseId }) }); return <Card level={1}><CardContent className="space-y-4 p-5"><div><h2 className="font-semibold">Alertas de shrinkage</h2><p className="text-sm text-text-secondary">Detecta pérdidas, sobreporcionamiento, robo o registros incompletos a partir de la variación.</p></div><DataState query={query}>{<Table headers={["Ingrediente", "Variación", "Costo", "Motivo", "Estado", "Detectado"]}>{(query.data ?? []).map((item) => <tr key={item.id}><td>{item.ingredientName ?? item.ingredientId}</td><td><Badge variant="destructive">{item.variancePercent.toFixed(1)}%</Badge></td><td>${item.varianceCost.toFixed(2)}</td><td>{item.reason ?? "Revisión requerida"}</td><td><Badge>{item.status}</Badge></td><td>{item.detectedAt ?? "-"}</td></tr>)}</Table>}</DataState></CardContent></Card>; }

function AuditView() { const { currentBranch } = useAppStore(); const { warehouseId } = useRestaurantInventoryContext(); const query = useQuery({ queryKey: ["restaurant-audit-log", currentBranch?.id, warehouseId], queryFn: () => fetchRestaurantAuditLog({ branchId: currentBranch?.id, warehouseId }) }); return <Card level={1}><CardContent className="space-y-4 p-5"><div><h2 className="font-semibold">Auditoría inmutable</h2><p className="text-sm text-text-secondary">Registro de cambios de inventario que no puede editarse desde el cliente.</p></div><DataState query={query}>{<Table headers={["Fecha", "Actor", "Acción", "Entidad", "Motivo", "Integridad"]}>{(query.data ?? []).map((item) => <tr key={item.id}><td>{item.createdAt}</td><td>{item.actorName ?? "-"}</td><td>{item.action}</td><td>{item.entityType} · {item.entityId}</td><td>{item.reason ?? "-"}</td><td><Badge variant={item.immutable ? "default" : "destructive"}>{item.immutable ? "Inmutable" : "Revisar"}</Badge></td></tr>)}</Table>}</DataState></CardContent></Card>; }

function DataState({ query, children }: { query: { isLoading: boolean; error: unknown; refetch: () => unknown }; children: React.ReactNode }) { if (query.isLoading) return <AsyncState state="loading" />; if (query.error) return <AsyncState state="error" onRetry={() => void query.refetch()} description={getApiErrorMessage(query.error, "El contrato de control avanzado aún no está disponible.")} />; return <>{children}</>; }
function Table({ headers, children }: { headers: string[]; children: React.ReactNode }) { return <div className="overflow-x-auto rounded-2xl border border-border-default"><table className="w-full min-w-[820px] text-left text-sm"><thead className="bg-surface-interactive"><tr>{headers.map((header) => <th key={header} className="px-3 py-3 font-medium">{header}</th>)}</tr></thead><tbody className="divide-y divide-border-default">{children}</tbody></table></div>; }
