"use client";

import { useState } from "react";
import { Check, ChevronLeft, ChevronRight, Plus, ScanLine, Trash2, X } from "lucide-react";
import { validateReceiptDraft, type ReceiptDraftLine } from "@/lib/restaurant-inventory";
import { InlineFeedback } from "@/components/design-system";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";

type Line = ReceiptDraftLine & { lotNumber: string; expirationDate: string };
type Editor = { id?: string; status?: "DRAFT" | "CONFIRMED" | "CANCELLED"; supplierId: string; warehouseId: string; receivedAt: string; invoice: string; notes: string; lines: Line[] };
type Preview = { items: Array<Record<string, unknown> & { ingredientId: string; purchaseQuantity: number; conversionFactor: number; inventoryQuantity: number; unitCost: number; totalCost: number }>; totalCost: number; totalInventoryQuantity: number };
type Option = { id: string; label: string; purchaseUnitId?: string };

const steps = ["Proveedor y almacén", "Ingredientes", "Lotes y vencimientos", "Vista previa", "Confirmación"];

export function RestaurantReceiptWizard({ editor, setEditor, ingredients, units, suppliers, warehouses, branchId, pending, preview, onPreview, onSave, onClose }: { editor: Editor; setEditor: (value: Editor) => void; ingredients: Option[]; units: Option[]; suppliers: Option[]; warehouses: Option[]; branchId?: string; pending: boolean; preview?: Preview; onPreview: () => void; onSave: () => void; onClose: () => void }) {
  const [step, setStep] = useState(1);
  const [quickCapture, setQuickCapture] = useState(true);
  const [errors, setErrors] = useState<Record<string, string>>({});
  const change = (key: keyof Editor, value: string) => setEditor({ ...editor, [key]: value });
  const updateLine = (index: number, key: keyof Line, value: string) => setEditor({ ...editor, lines: editor.lines.map((line, lineIndex) => lineIndex === index ? { ...line, [key]: value } : line) });
  const validate = () => { const next = validateReceiptDraft(editor); setErrors(next); return next; };
  const next = () => {
    const currentErrors = validate();
    if (step === 1 && (currentErrors.warehouseId || currentErrors.receivedAt)) return;
    if (step === 2 && (currentErrors.lines || Object.keys(currentErrors).some((key) => key.includes("ingredient") || key.includes("unit") || key.includes("quantity") || key.includes("cost")))) return;
    if (step === 3 && Object.keys(currentErrors).some((key) => key.includes("lot") || key.includes("expiration"))) return;
    if (step === 3) { onPreview(); setStep(4); return; }
    if (step < 5) setStep(step + 1);
  };
  const previous = () => setStep((value) => Math.max(1, value - 1));
  const compact = quickCapture ? "text-base md:text-lg" : "text-sm";
  return <Card level={2}><CardContent className="space-y-5 p-4 md:p-6">
    <div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-sm text-text-secondary">{editor.id ? "Editar borrador" : "Nueva entrada"}</p><h2 className="text-xl font-semibold">Entrada de mercancía</h2><p className="mt-1 text-sm text-text-secondary">Completa el flujo y revisa el impacto antes de confirmar.</p></div><div className="flex gap-2"><Button size="sm" variant={quickCapture ? "default" : "secondary"} onClick={() => setQuickCapture((value) => !value)}><ScanLine className="size-4" />{quickCapture ? "Captura rápida activa" : "Captura rápida"}</Button><Button variant="ghost" onClick={onClose} aria-label="Cerrar editor"><X className="size-4" /></Button></div></div>
    <ol className="grid gap-2 sm:grid-cols-5" aria-label="Pasos de la entrada">{steps.map((label, index) => { const number = index + 1; return <li key={label}><button type="button" onClick={() => number <= step && setStep(number)} className={`w-full rounded-xl border px-2 py-2 text-left ${number === step ? "border-primary bg-primary/10" : number < step ? "border-success/40 bg-success/5" : "border-border-default"}`}><span className="flex items-center gap-2 text-xs font-semibold"><span className="grid size-6 place-items-center rounded-full bg-surface-interactive">{number < step ? <Check className="size-3" /> : number}</span>{label}</span></button></li>; })}</ol>
    {step === 1 ? <section className="space-y-4"><h3 className="font-semibold">1. Proveedor y almacén</h3><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Select id="receipt-warehouse" label="Almacén" value={editor.warehouseId} options={warehouses} onChange={(value) => change("warehouseId", value)} error={errors.warehouseId} /><Select id="receipt-supplier" label="Proveedor" value={editor.supplierId} options={suppliers} onChange={(value) => change("supplierId", value)} optional /><Field id="receipt-date" label="Fecha" type="datetime-local" value={editor.receivedAt} onChange={(value) => change("receivedAt", value)} error={errors.receivedAt} /><Field id="receipt-invoice" label="Factura" value={editor.invoice} onChange={(value) => change("invoice", value)} /></div><div><Label htmlFor="receipt-notes">Observaciones</Label><Input id="receipt-notes" value={editor.notes} onChange={(event) => change("notes", event.target.value)} /></div></section> : null}
    {step === 2 ? <section className="space-y-4"><div className="flex items-center justify-between gap-3"><div><h3 className="font-semibold">2. Ingredientes y cantidades</h3><p className="text-sm text-text-secondary">La conversión a unidad de inventario la calcula el backend.</p></div><Button size="sm" variant="secondary" onClick={() => setEditor({ ...editor, lines: [...editor.lines, emptyLine()] })}><Plus className="size-4" />Agregar línea</Button></div>{errors.lines ? <p className="text-sm text-danger">{errors.lines}</p> : null}<div className="space-y-3">{editor.lines.map((line, index) => <div key={`${index}-${line.ingredientId}`} className={`rounded-2xl border border-border-default p-3 ${quickCapture ? "bg-surface-interactive/30" : ""}`}><div className="grid gap-3 md:grid-cols-[2fr_1.2fr_1fr_1fr_auto]"><Select id={`receipt-ingredient-${index}`} label="Ingrediente" value={line.ingredientId} options={ingredients} onChange={(value) => { const ingredient = ingredients.find((item) => item.id === value); setEditor({ ...editor, lines: editor.lines.map((current, lineIndex) => lineIndex === index ? { ...current, ingredientId: value, purchaseUnitId: ingredient?.purchaseUnitId ?? current.purchaseUnitId } : current) }); }} error={errors[`line-${index}-ingredient`]} /><Select id={`receipt-unit-${index}`} label="Unidad de compra" value={line.purchaseUnitId} options={units} onChange={(value) => updateLine(index, "purchaseUnitId", value)} error={errors[`line-${index}-unit`]} /><Field id={`receipt-quantity-${index}`} label="Cantidad comprada" type="number" value={line.purchaseQuantity} onChange={(value) => updateLine(index, "purchaseQuantity", value)} error={errors[`line-${index}-quantity`]} className={compact} /><Field id={`receipt-cost-${index}`} label="Costo unitario" type="number" value={line.unitCost} onChange={(value) => updateLine(index, "unitCost", value)} error={errors[`line-${index}-cost`]} className={compact} /><Button variant="ghost" size="sm" onClick={() => setEditor({ ...editor, lines: editor.lines.filter((_, lineIndex) => lineIndex !== index) })} aria-label={`Eliminar ingrediente ${index + 1}`}><Trash2 className="size-4" /></Button></div></div>)}</div></section> : null}
    {step === 3 ? <section className="space-y-4"><div><h3 className="font-semibold">3. Lotes y vencimientos</h3><p className="text-sm text-text-secondary">Registra la trazabilidad de cada línea antes de calcular el impacto.</p></div>{editor.lines.map((line, index) => <div key={`${index}-${line.ingredientId}`} className="grid gap-3 rounded-2xl border border-border-default p-3 sm:grid-cols-[2fr_1fr_1fr]"><p className="flex items-center font-medium">{ingredients.find((item) => item.id === line.ingredientId)?.label ?? "Ingrediente pendiente"}</p><Field id={`receipt-lot-${index}`} label="Lote" value={line.lotNumber} onChange={(value) => updateLine(index, "lotNumber", value)} error={errors[`line-${index}-lot`]} /><Field id={`receipt-expiration-${index}`} label="Vencimiento" type="date" value={line.expirationDate} onChange={(value) => updateLine(index, "expirationDate", value)} error={errors[`line-${index}-expiration`]} /></div>)}</section> : null}
    {step === 4 ? <section className="space-y-4"><div><h3 className="font-semibold">4. Vista previa e impacto esperado</h3><p className="text-sm text-text-secondary">No hay movimientos aplicados hasta confirmar el documento.</p></div>{preview ? <PreviewImpact preview={preview} /> : <InlineFeedback tone="warning" title="Vista previa pendiente">Calcula la vista previa para conocer cantidades, conversiones y costo estimado.</InlineFeedback>}</section> : null}
    {step === 5 ? <section className="space-y-4"><h3 className="font-semibold">5. Confirmación</h3>{preview ? <><PreviewImpact preview={preview} /><InlineFeedback tone="warning" title="Confirmación irreversible">Al confirmar se actualizarán existencias, lotes, movimientos y costo promedio del almacén seleccionado.</InlineFeedback><p className="text-sm text-text-secondary">Primero se guardará el documento como borrador y luego podrás confirmar la aplicación.</p></> : <InlineFeedback tone="danger" title="Falta la vista previa">Regresa al paso anterior y calcula el impacto antes de continuar.</InlineFeedback>}</section> : null}
    <div className="flex flex-wrap justify-between gap-2 border-t border-border-default pt-4"><Button variant="secondary" disabled={step === 1 || pending} onClick={previous}><ChevronLeft className="size-4" />Anterior</Button><div className="flex gap-2"><Button variant="secondary" onClick={onClose}>Cancelar</Button>{step < 3 ? <Button disabled={pending} onClick={next}>Siguiente<ChevronRight className="size-4" /></Button> : step === 3 ? <Button disabled={pending} onClick={next}>{pending ? "Calculando…" : "Calcular impacto"}<ChevronRight className="size-4" /></Button> : step === 4 ? <Button disabled={!preview || pending} onClick={() => setStep(5)}>Revisar confirmación<ChevronRight className="size-4" /></Button> : <Button disabled={!preview || pending} onClick={onSave}><Check className="size-4" />Guardar y confirmar</Button>}</div></div>
    {!branchId ? <InlineFeedback tone="warning" title="Sucursal requerida">No hay sucursal activa para guardar la entrada.</InlineFeedback> : null}
  </CardContent></Card>;
}

function PreviewImpact({ preview }: { preview: Preview }) { return <div className="space-y-4"><div className="grid gap-3 sm:grid-cols-3"><ImpactCard label="Existencias que ingresan" value={`${preview.totalInventoryQuantity} unidades de inventario`} /><ImpactCard label="Costo recibido" value={`$${preview.totalCost.toFixed(2)}`} /><ImpactCard label="Costo promedio" value="Se recalcula al confirmar" /></div><div className="overflow-x-auto rounded-2xl border border-border-default"><table className="w-full min-w-[680px] text-left text-sm"><thead className="bg-surface-interactive text-text-secondary"><tr>{["Ingrediente", "Comprado", "Conversión", "Ingresa", "Costo", "Total"].map((header) => <th key={header} className="px-4 py-3 font-medium">{header}</th>)}</tr></thead><tbody className="divide-y divide-border-default">{preview.items.map((item) => <tr key={item.ingredientId}><td className="px-4 py-3">{String(item.ingredientName ?? item.ingredientId)}</td><td className="px-4 py-3">{item.purchaseQuantity}</td><td className="px-4 py-3">{item.conversionFactor}</td><td className="px-4 py-3 font-medium">{item.inventoryQuantity}</td><td className="px-4 py-3">${item.unitCost.toFixed(2)}</td><td className="px-4 py-3">${item.totalCost.toFixed(2)}</td></tr>)}</tbody></table></div></div>; }
function ImpactCard({ label, value }: { label: string; value: string }) { return <Card level={1}><CardContent className="p-4"><p className="text-xs text-text-secondary">{label}</p><p className="mt-2 font-semibold">{value}</p></CardContent></Card>; }
function Select({ id, label, value, options, onChange, error, optional }: { id: string; label: string; value: string; options: Option[]; onChange: (value: string) => void; error?: string; optional?: boolean }) { return <div><Label htmlFor={id}>{label}{optional ? " · opcional" : ""}</Label><select id={id} className="h-11 w-full rounded-2xl border border-border-default bg-surface-elevated px-3" value={value} onChange={(event) => onChange(event.target.value)}><option value="">Seleccionar</option>{options.map((option) => <option key={option.id} value={option.id}>{option.label}</option>)}</select>{error ? <p className="mt-1 text-xs text-danger">{error}</p> : null}</div>; }
function Field({ id, label, value, onChange, type = "text", error, className = "" }: { id: string; label: string; value: string; onChange: (value: string) => void; type?: string; error?: string; className?: string }) { return <div><Label htmlFor={id}>{label}</Label><Input className={className} id={id} type={type} value={value} onChange={(event) => onChange(event.target.value)} />{error ? <p className="mt-1 text-xs text-danger">{error}</p> : null}</div>; }
function emptyLine(): Line { return { ingredientId: "", purchaseUnitId: "", purchaseQuantity: "", unitCost: "", lotNumber: "", expirationDate: "" }; }
