"use client";

import { useState } from "react";
import { Download, Save } from "lucide-react";
import { useQuery } from "@tanstack/react-query";
import { fetchRestaurantReport, getApiErrorMessage } from "@/lib/backend";
import { useAppStore } from "@/store/app-store";
import { AsyncState } from "@/components/async-state";
import { InlineFeedback, PageHeader } from "@/components/design-system";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";

const reports = [["kardex", "Kardex"], ["valued-stock", "Existencias valorizadas"], ["consumption-by-recipe", "Consumo"], ["waste-by-reason", "Desperdicios"], ["expiry", "Vencimientos"], ["count-variances", "Variación teórico vs contado"], ["theoretical-vs-real", "Consumo teórico vs real"], ["purchase-suggestions", "Sugerencias de compra"]];
type Filters = { branchId: string; warehouseId: string; from: string; to: string; ingredientId: string; recipeId: string };
const empty: Filters = { branchId: "", warehouseId: "", from: "", to: "", ingredientId: "", recipeId: "" };

export function RestaurantReportsWorkspace({ initialReport }: { initialReport?: string }) { const { currentUser, currentBranch } = useAppStore(); const key = `restaurant-report-filters:${currentUser.id}:${currentBranch?.id ?? "none"}`; const [report, setReport] = useState(initialReport ?? "kardex"); const [filters, setFilters] = useState<Filters>({ ...empty, branchId: currentBranch?.id ?? "" }); const [saved, setSaved] = useState(false); const query = useQuery({ queryKey: ["restaurant-decision-report", report, filters], queryFn: () => fetchRestaurantReport(report, { ...filters, page: 1, pageSize: 50 }) }); const update = (keyName: keyof Filters, value: string) => setFilters({ ...filters, [keyName]: value }); const saveFilters = () => { window.localStorage.setItem(key, JSON.stringify(filters)); setSaved(true); }; const loadFilters = () => { try { const value = JSON.parse(window.localStorage.getItem(key) ?? "{}"); setFilters({ ...empty, ...value }); setSaved(true); } catch { setSaved(false); } }; return <div className="space-y-5"><PageHeader eyebrow="Reportes" title="Reportes para decidir" description="Guarda filtros frecuentes y exporta los resultados para operación o dirección." actions={<span className="flex gap-2"><Button variant="secondary" onClick={saveFilters}><Save className="size-4" />Guardar filtros</Button><Button variant="secondary" onClick={loadFilters}>Cargar guardados</Button></span>} /><Card level={1}><CardContent className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><div><Label htmlFor="decision-report">Reporte</Label><select id="decision-report" className="h-11 w-full rounded-2xl border border-border-default bg-surface-elevated px-3" value={report} onChange={(event) => setReport(event.target.value)}>{reports.map(([id, label]) => <option key={id} value={id}>{label}</option>)}</select></div>{Object.entries(filters).map(([keyName, value]) => <div key={keyName}><Label htmlFor={`saved-filter-${keyName}`}>{filterLabel(keyName)}</Label><Input id={`saved-filter-${keyName}`} type={keyName === "from" || keyName === "to" ? "date" : "text"} value={value} onChange={(event) => update(keyName as keyof Filters, event.target.value)} placeholder={keyName === "branchId" ? "Sucursal actual" : "Opcional"} /></div>)}</CardContent></Card>{saved ? <InlineFeedback tone="success" title="Filtros guardados">Estos filtros quedan disponibles para este usuario y sucursal.</InlineFeedback> : null}{query.isLoading ? <AsyncState state="loading" /> : query.error ? <AsyncState state="error" onRetry={() => void query.refetch()} description={getApiErrorMessage(query.error, "No fue posible cargar el reporte.")} /> : query.data ? <ReportResult report={report} data={query.data} /> : null}</div>; }
function ReportResult({ report, data }: { report: string; data: import("@/lib/contracts").RestaurantReportDto }) { const rows = data.rows.map((row) => data.columns.map((column) => row[column.key] ?? "-")); return <div className="space-y-4"><div className="flex flex-wrap justify-between gap-2"><div className="flex gap-2">{data.summary.map((item) => <Badge key={item.label} variant="secondary">{item.label}: {item.value}</Badge>)}</div><span className="flex gap-2"><Button variant="secondary" onClick={() => exportCsv(`${report}.csv`, [data.columns.map((column) => column.label), ...rows])}><Download className="size-4" />CSV</Button><Button variant="secondary" onClick={() => window.print()}>PDF</Button></span></div>{rows.length ? <Card level={2}><CardContent className="p-0"><div className="overflow-x-auto"><table className="w-full min-w-[850px] text-left text-sm"><thead className="bg-surface-interactive"><tr>{data.columns.map((column) => <th key={column.key} className="px-3 py-3">{column.label}</th>)}</tr></thead><tbody className="divide-y divide-border-default">{data.rows.map((row, index) => <tr key={String(row.id ?? index)}>{data.columns.map((column) => <td key={column.key} className="px-3 py-3">{String(row[column.key] ?? "-")}</td>)}</tr>)}</tbody></table></div></CardContent></Card> : <InlineFeedback tone="info" title="Sin resultados">Prueba otro rango de fechas o cambia el almacén para encontrar movimientos.</InlineFeedback>}{report === "theoretical-vs-real" || report === "count-variances" ? <InlineFeedback tone="warning" title="Variación teórico vs real">Revisa las filas con diferencia y genera un conteo físico o una acción de ajuste.</InlineFeedback> : null}</div>; }
function filterLabel(key: string) { return { branchId: "Sucursal", warehouseId: "Almacén", from: "Desde", to: "Hasta", ingredientId: "Ingrediente", recipeId: "Receta" }[key as keyof Filters] ?? key; }
function exportCsv(filename: string, rows: unknown[][]) { const csv = rows.map((row) => row.map((value) => `"${String(value ?? "").replaceAll('"', '""')}"`).join(",")).join("\n"); const url = URL.createObjectURL(new Blob([csv], { type: "text/csv;charset=utf-8" })); const anchor = document.createElement("a"); anchor.href = url; anchor.download = filename; anchor.click(); URL.revokeObjectURL(url); }
