"use client";

import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Activity, BookOpenCheck, ShieldCheck, Users } from "lucide-react";
import { toast } from "sonner";
import { createScorecardCompetency, fetchBiasValidations, fetchEvaluatorCalibration, fetchInterviewScorecardContext, fetchRecruitmentInterviews, fetchScorecardCompetencies, replaceScorecardAssignments, runBiasValidation, runEvaluatorCalibration } from "@/lib/backend";
import { useAppStore } from "@/store/app-store";
import { InlineFeedback } from "@/components/design-system";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";

export function ScorecardGovernanceConsole() {
  const queryClient = useQueryClient();
  const { tenantUsers, can } = useAppStore();
  const [competency, setCompetency] = useState({ code: "", name: "", category: "" });
  const [interviewId, setInterviewId] = useState("");
  const [evaluatorId, setEvaluatorId] = useState("");
  const [criterionIds, setCriterionIds] = useState<string[]>([]);
  const [anonymousReview, setAnonymousReview] = useState(true);
  const [bias, setBias] = useState({ populationField: "grupo_demografico", referenceName: "Referencia", referenceTotal: 100, referenceSelected: 50, comparisonName: "Comparación", comparisonTotal: 100, comparisonSelected: 40 });
  const competencies = useQuery({ queryKey: ["scorecard-competencies"], queryFn: () => fetchScorecardCompetencies(true) });
  const interviews = useQuery({ queryKey: ["scorecard-assignment-interviews"], queryFn: () => fetchRecruitmentInterviews({ page: 1, pageSize: 100 }) });
  const context = useQuery({ queryKey: ["scorecard-context", interviewId], queryFn: () => fetchInterviewScorecardContext(interviewId), enabled: Boolean(interviewId) });
  const calibration = useQuery({ queryKey: ["scorecard-calibration"], queryFn: fetchEvaluatorCalibration });
  const validations = useQuery({ queryKey: ["scorecard-bias-validations"], queryFn: fetchBiasValidations });
  const createCompetency = useMutation({ mutationFn: () => createScorecardCompetency({ ...competency, description: "", behavioralAnchors: {} }), onSuccess: async () => { setCompetency({ code: "", name: "", category: "" }); toast.success("Competencia agregada a la biblioteca"); await queryClient.invalidateQueries({ queryKey: ["scorecard-competencies"] }); } });
  const assign = useMutation({ mutationFn: () => replaceScorecardAssignments(interviewId, [{ evaluatorUserId: evaluatorId, criterionIds, anonymousReview }]), onSuccess: () => toast.success("Preguntas asignadas al evaluador") });
  const calculate = useMutation({ mutationFn: runEvaluatorCalibration, onSuccess: async () => { toast.success("Calibración recalculada"); await queryClient.invalidateQueries({ queryKey: ["scorecard-calibration"] }); } });
  const validate = useMutation({ mutationFn: () => runBiasValidation({ populationField: bias.populationField, referenceGroup: { name: bias.referenceName, total: bias.referenceTotal, selected: bias.referenceSelected }, comparisonGroup: { name: bias.comparisonName, total: bias.comparisonTotal, selected: bias.comparisonSelected } }), onSuccess: async () => { toast.success("Análisis estadístico registrado"); await queryClient.invalidateQueries({ queryKey: ["scorecard-bias-validations"] }); } });

  return <section className="space-y-5"><div><h2 className="text-xl font-semibold">Gobierno y calidad de evaluación</h2><p className="text-sm text-text-secondary">Biblioteca compartida, revisión ciega, calibración histórica y controles estadísticos auditables.</p></div><div className="grid gap-5 xl:grid-cols-2">
    <Card level={2}><CardHeader><CardTitle><span className="inline-flex items-center gap-2"><BookOpenCheck className="size-5" />Biblioteca global de competencias</span></CardTitle></CardHeader><CardContent className="space-y-4"><div className="grid gap-2 sm:grid-cols-3"><Input placeholder="Código" value={competency.code} onChange={(event) => setCompetency({ ...competency, code: event.target.value.toUpperCase() })} /><Input placeholder="Competencia" value={competency.name} onChange={(event) => setCompetency({ ...competency, name: event.target.value })} /><Input placeholder="Categoría" value={competency.category} onChange={(event) => setCompetency({ ...competency, category: event.target.value })} /></div>{can("vacancies.update") ? <Button onClick={() => createCompetency.mutate()} disabled={!competency.code || !competency.name || createCompetency.isPending}>Agregar competencia</Button> : null}<div className="flex flex-wrap gap-2">{competencies.data?.map((item) => <Badge key={item.id} variant={item.isActive ? "secondary" : "outline"}>{item.code} · {item.name}</Badge>)}</div></CardContent></Card>
    <Card level={2}><CardHeader><CardTitle><span className="inline-flex items-center gap-2"><Users className="size-5" />Asignación y revisión anónima</span></CardTitle></CardHeader><CardContent className="space-y-4"><Select value={interviewId || undefined} onValueChange={(value) => { setInterviewId(value); setCriterionIds([]); }}><SelectTrigger><SelectValue placeholder="Selecciona entrevista" /></SelectTrigger><SelectContent>{interviews.data?.data.map((item) => <SelectItem key={item.id} value={item.id}>{item.title} · {item.application?.candidate.fullName}</SelectItem>)}</SelectContent></Select><Select value={evaluatorId || undefined} onValueChange={setEvaluatorId}><SelectTrigger><SelectValue placeholder="Selecciona evaluador" /></SelectTrigger><SelectContent>{tenantUsers.map((user) => <SelectItem key={user.id} value={user.id}>{user.fullName}</SelectItem>)}</SelectContent></Select><div className="max-h-40 space-y-2 overflow-y-auto rounded-xl border p-3">{context.data?.template?.criteria.map((criterion) => <label key={criterion.id} className="flex items-center gap-2 text-sm"><input type="checkbox" checked={criterionIds.includes(criterion.id)} onChange={(event) => setCriterionIds((current) => event.target.checked ? [...current, criterion.id] : current.filter((id) => id !== criterion.id))} />{criterion.label}</label>) ?? <p className="text-sm text-text-secondary">Selecciona una entrevista con plantilla.</p>}</div><label className="flex gap-2 text-sm"><input type="checkbox" checked={anonymousReview} onChange={(event) => setAnonymousReview(event.target.checked)} />Ocultar identidad hasta que finalicen las evaluaciones</label><Button onClick={() => assign.mutate()} disabled={!interviewId || !evaluatorId || !criterionIds.length || assign.isPending}>Guardar asignación</Button></CardContent></Card>
    <Card level={2}><CardHeader><CardTitle><span className="inline-flex items-center gap-2"><Activity className="size-5" />Calibración de evaluadores</span></CardTitle></CardHeader><CardContent className="space-y-4"><Button variant="secondary" onClick={() => calculate.mutate()} disabled={calculate.isPending}>Calcular últimos 180 días</Button>{calibration.data?.length ? <div className="space-y-2">{calibration.data.slice(0, 8).map((item) => <div key={item.id} className="rounded-xl bg-surface-section p-3 text-sm"><p className="font-medium">{item.evaluator.firstName} {item.evaluator.lastName} · n={item.sampleSize}</p><p className="text-text-secondary">Acuerdo {Number(item.agreementRate).toFixed(1)}% · evidencia {Number(item.evidenceRate).toFixed(1)}% · desviación {Number(item.meanDeviation).toFixed(1)}</p></div>)}</div> : <p className="text-sm text-text-secondary">Aún no hay una muestra histórica calculada.</p>}</CardContent></Card>
    <Card level={2}><CardHeader><CardTitle><span className="inline-flex items-center gap-2"><ShieldCheck className="size-5" />Validación de indicadores de sesgo</span></CardTitle></CardHeader><CardContent className="space-y-4"><InlineFeedback tone="warning" title="Uso responsable">Prueba de tasas de selección y significancia sobre datos agregados. No demuestra causalidad ni reemplaza validación independiente.</InlineFeedback><Input value={bias.populationField} onChange={(event) => setBias({ ...bias, populationField: event.target.value })} placeholder="Dimensión analizada" /><div className="grid grid-cols-3 gap-2"><Input value={bias.referenceName} onChange={(event) => setBias({ ...bias, referenceName: event.target.value })} /><Input type="number" value={bias.referenceTotal} onChange={(event) => setBias({ ...bias, referenceTotal: Number(event.target.value) })} /><Input type="number" value={bias.referenceSelected} onChange={(event) => setBias({ ...bias, referenceSelected: Number(event.target.value) })} /><Input value={bias.comparisonName} onChange={(event) => setBias({ ...bias, comparisonName: event.target.value })} /><Input type="number" value={bias.comparisonTotal} onChange={(event) => setBias({ ...bias, comparisonTotal: Number(event.target.value) })} /><Input type="number" value={bias.comparisonSelected} onChange={(event) => setBias({ ...bias, comparisonSelected: Number(event.target.value) })} /></div><Button onClick={() => validate.mutate()} disabled={validate.isPending}>Ejecutar análisis</Button>{validations.data?.slice(0, 3).map((item) => <div key={item.id} className="rounded-xl border p-3 text-sm"><div className="flex justify-between"><strong>{item.populationField}</strong><Badge>{item.status}</Badge></div><p className="text-text-secondary">n={item.sampleSize} · ratio {item.selectionRateRatio == null ? "N/D" : Number(item.selectionRateRatio).toFixed(3)} · p {item.pValue == null ? "N/D" : Number(item.pValue).toFixed(4)}</p></div>)}</CardContent></Card>
  </div></section>;
}
